#ifdef UNIT_TESTS
/datum/unit_test/ms13_rail_vehicles/Run()
	var/test_z = run_loc_floor_bottom_left.z
	for(var/turf/ground in block(locate(10, 10, test_z), locate(55, 55, test_z)))
		ground.ChangeTurf(/turf/open/floor/plating)
		for(var/obj/obstacle in ground)
			qdel(obstacle)
	var/list/base_impact = measure_impact(500, 1, 20, test_z)
	var/list/heavy_impact = measure_impact(1000, 1, 20, test_z)
	var/list/fast_impact = measure_impact(500, 2, 20, test_z)
	var/list/armored_impact = measure_impact(500, 1, 80, test_z)
	if(abs(heavy_impact[1] - 2 * base_impact[1]) > 0.1 || abs(fast_impact[1] - 4 * base_impact[1]) > 0.1)
		Fail("Collision damage did not scale linearly with mass and quadratically with speed.")
	if(armored_impact[1] <= base_impact[1] || armored_impact[2] >= base_impact[2])
		Fail("Contact armor did not improve damage delivery and reduce self-damage.")
	check_mounts(test_z)
	// Shoving moves the whole struck vehicle, including loose cargo. A blocked shove cannot recurse.
	var/obj/structure/ms13_vehicle_frame/jeep_front/rammer = allocate(/obj/structure/ms13_vehicle_frame/jeep_front, locate(20, 20, test_z))
	var/obj/structure/ms13_vehicle_frame/jeep_front/victim = allocate(/obj/structure/ms13_vehicle_frame/jeep_front, locate(20, 18, test_z))
	var/obj/item/cargo = allocate(/obj/item, get_turf(victim))
	rammer.vehicle.speed = 2
	if(!rammer.vehicle.do_move(SOUTH, TRUE) || victim.y != 17 || cargo.y != 17 || rammer.y != 19)
		Fail("Vehicle collision failed to shove an intact formation and its cargo.")
	var/obj/structure/blocker = allocate(/obj/structure, locate(20, 16, test_z))
	blocker.density = TRUE
	if(rammer.vehicle.try_shove_vehicle(victim.vehicle, SOUTH) || victim.y != 17)
		Fail("Vehicle shoved through a blocked destination.")
	qdel(blocker)
	victim.vehicle.mass_per_frame = 100000
	if(rammer.vehicle.try_shove_vehicle(victim.vehicle, SOUTH))
		Fail("A light vehicle shoved an excessively heavy vehicle.")
	clear_vehicle(rammer.vehicle)
	clear_vehicle(victim.vehicle)
	check_corridors(test_z)
	// Side plating still takes the impact when an in-path obstacle hits a missing front panel.
	rammer = allocate(/obj/structure/ms13_vehicle_frame/jeep_front, locate(20, 20, test_z))
	for(var/obj/structure/window/ms13_vehicle_wall/panel as anything in rammer.vehicle.walls.Copy())
		if(panel.dir == SOUTH)
			qdel(panel)
	var/turf/house_wall = locate(20, 19, test_z)
	house_wall = house_wall.ChangeTurf(/turf/closed/wall)
	if(rammer.vehicle.can_move(SOUTH))
		Fail("Vehicle ignored an in-path house wall.")
	var/integrity_before = house_wall.get_integrity()
	var/frame_before = rammer.get_integrity()
	rammer.vehicle.speed = 1
	rammer.vehicle.ram_obstacles(SOUTH, rammer.vehicle.get_manifest())
	if(house_wall.get_integrity() >= integrity_before)
		Fail("Side hull collision did not damage the house wall.")
	if(rammer.get_integrity() != frame_before)
		Fail("Missing front plating bypassed the remaining side armor.")
	house_wall.ChangeTurf(/turf/open/floor/plating)
	var/obj/structure/table/ms13/low_wall/brick/low_wall = allocate(/obj/structure/table/ms13/low_wall/brick, locate(20, 19, test_z))
	var/obj/structure/window/fulltile/ms13/glass/window = allocate(/obj/structure/window/fulltile/ms13/glass, get_turf(low_wall))
	var/low_before = low_wall.get_integrity()
	var/window_before = window.get_integrity()
	rammer.vehicle.stop_motion()
	rammer.vehicle.speed = 1
	rammer.vehicle.do_move(SOUTH, TRUE)
	if(!QDELETED(low_wall) && low_wall.get_integrity() >= low_before)
		Fail("Vehicle failed to damage an in-path low wall.")
	if(!QDELETED(window) && window.get_integrity() >= window_before)
		Fail("Vehicle failed to damage a window stacked on a low wall.")
	if(!QDELETED(low_wall) && low_wall.density && rammer.y != 20)
		Fail("Vehicle clipped through a surviving low wall.")
	qdel(low_wall)
	qdel(window)
	clear_vehicle(rammer.vehicle)
	// A real loop of guide rails, with room for the rigid car to sweep around its pivot.
	var/list/route = list()
	for(var/x in 26 to 35)
		route += locate(x, 35, test_z)
	for(var/y = 34, y >= 25, y--)
		route += locate(35, y, test_z)
	for(var/x = 34, x >= 25, x--)
		route += locate(x, 25, test_z)
	for(var/y in 26 to 35)
		route += locate(25, y, test_z)
	route += locate(26, 35, test_z)
	for(var/turf/rail_tile as anything in route)
		if(!(locate(/obj/structure/ms13_rail) in rail_tile))
			allocate(/obj/structure/ms13_rail, rail_tile)
	var/obj/structure/ms13_vehicle_frame/tram/tram = allocate(/obj/structure/ms13_vehicle_frame/tram, locate(25, 35, test_z))
	var/datum/ms13_ground_vehicle/rail/train = tram.vehicle
	if(length(train.frames) != 8)
		Fail("Tram is not 2x4.")
	var/obj/structure/chair/ms13_vehicle_seat/driver_seat = locate() in get_turf(tram)
	var/mob/living/carbon/human/consistent/driver = allocate(/mob/living/carbon/human/consistent, get_turf(tram))
	driver_seat.user_buckle_mob(driver, driver)
	for(var/direction in GLOB.cardinals)
		driver_seat.setDir(direction)
		if(driver_seat.layer >= MOB_LAYER)
			Fail("Driver's seat was drawn over its driver.")
		for(var/mutable_appearance/monitor as anything in driver_seat.update_overlays())
			if(monitor.layer >= MOB_LAYER)
				Fail("Dashboard overlay was drawn over its driver.")
	driver_seat.setDir(train.dir)
	// Intermediate obstacles must block a turn even when both endpoint footprints are clear.
	blocker = allocate(/obj/structure, locate(23, 37, test_z))
	blocker.density = TRUE
	if(train.can_rotate(EAST))
		Fail("Train rotated through an obstacle in its turning apron.")
	qdel(blocker)
	cargo = allocate(/obj/item, get_turf(tram))
	var/list/parents = train.find_rail_routes()
	if(!parents[locate(35, 25, test_z)] || length(parents) != 40)
		Fail("Rail search did not find the complete connected loop.")
	train.set_ignition(TRUE)
	train.start_engine()
	var/fuel_before = train.fuel_tank.reagents.total_volume
	train.rail_route = route.Copy()
	train.moving = TRUE
	train.speed = 3
	var/list/headings = list()
	for(var/tick in 1 to 90)
		train.next_move_time = 0
		train.next_acceleration_time = 0
		train.movement_tick(train.movement_generation)
		headings |= train.dir
		if(!train.moving)
			break
	if(train.moving || train.speed || get_turf(tram) != locate(26, 35, test_z) || cargo.loc != tram.loc || length(headings) != 4 || driver.buckled != driver_seat || driver.loc != tram.loc)
		Fail("Autopilot failed a full E/S/W/N/E loop, cargo transport, or its final stop.")
	if(train.fuel_tank.reagents.total_volume >= fuel_before)
		Fail("Rail movement did not consume normal vehicle fuel.")
	if(train.do_move(NORTH, TRUE))
		Fail("Train drove off its guide rail.")
	var/obj/structure/ms13_rail/removed = locate() in get_step(tram, EAST)
	qdel(removed)
	if(train.do_move(EAST, TRUE))
		Fail("Train ignored destroyed rails.")
	clear_vehicle(train)
	// Someone standing on the ground it is being built over rides in it rather than blocking the build.
	var/mob/living/carbon/human/consistent/bystander = allocate(/mob/living/carbon/human/consistent, locate(40, 40, test_z))
	var/obj/structure/ms13_vehicle_frame/tram/train/large = allocate(/obj/structure/ms13_vehicle_frame/tram/train, locate(40, 40, test_z))
	if(QDELETED(large) || !large.vehicle)
		Fail("A train refused to assemble around a bystander.")
	if(length(large.vehicle.frames) != 18)
		Fail("Train is not 3x6.")
	if(bystander.loc != get_turf(large))
		Fail("Assembling a train moved a bystander.")
	clear_vehicle(large.vehicle)
	qdel(bystander)
	// The guide rail can run under the middle of a car, not just under its front-left corner.
	var/obj/structure/ms13_vehicle_frame/tram/offset_car = allocate(/obj/structure/ms13_vehicle_frame/tram, locate(41, 51, test_z))
	var/datum/ms13_ground_vehicle/rail/offset_vehicle = offset_car.vehicle
	var/obj/structure/ms13_vehicle_frame/middle
	for(var/obj/structure/ms13_vehicle_frame/frame as anything in offset_vehicle.frames)
		if(frame.forward_offset == -1 && frame.right_offset == 1)
			middle = frame
	for(var/travelled in -1 to 3)
		var/turf/rail_tile = locate(middle.x, middle.y - travelled, test_z)
		if(!ms13_rail_at(rail_tile))
			allocate(/obj/structure/ms13_rail, rail_tile)
	if(offset_vehicle.rail_frame() != middle)
		Fail("The car did not ride the rail line running under its middle.")
	if(!length(offset_vehicle.find_rail_routes()))
		Fail("A car riding the line off its pivot found no route along it.")
	if(!offset_vehicle.do_move(offset_vehicle.dir, TRUE))
		Fail("A car riding the line off its pivot refused to follow it.")
	if(offset_vehicle.do_move(turn(offset_vehicle.dir, 90), TRUE))
		Fail("A car drove off the rail line sideways.")
	clear_vehicle(offset_vehicle)

/datum/unit_test/ms13_rail_vehicles/proc/clear_vehicle(datum/ms13_ground_vehicle/vehicle)
	vehicle.stop_motion()
	for(var/atom/movable/component as anything in (vehicle.get_all_parts() | vehicle.get_manifest()))
		qdel(component)

/datum/unit_test/ms13_rail_vehicles/proc/check_mounts(test_z)
	var/obj/structure/ms13_vehicle_frame/jeep_front/jeep = allocate(/obj/structure/ms13_vehicle_frame/jeep_front, locate(20, 20, test_z))
	var/datum/ms13_ground_vehicle/vehicle = jeep.vehicle
	var/obj/structure/ms13_vehicle_part/engine/engine = vehicle.engine
	if(engine.density || !vehicle.blocks_vehicle(engine))
		Fail("Walk-over engine did not block vehicle collisions independently of mob density.")
	var/obj/structure/ms13_vehicle_part/exterior_equipment/camera/front_camera = jeep.spawn_part(/obj/structure/ms13_vehicle_part/exterior_equipment/camera)
	var/obj/structure/ms13_vehicle_part/exterior_equipment/camera/side_camera = jeep.spawn_part(/obj/structure/ms13_vehicle_part/exterior_equipment/camera, 90)
	var/obj/structure/window/ms13_vehicle_wall/front_panel
	var/obj/structure/window/ms13_vehicle_wall/side_panel
	for(var/obj/structure/window/ms13_vehicle_wall/panel as anything in vehicle.walls)
		if(panel.parent_frame != jeep)
			continue
		if(panel.dir == jeep.dir)
			front_panel = panel
		if(panel.dir == turn(jeep.dir, 90))
			side_panel = panel
	front_panel.update_integrity(1)
	if(!QDELETED(front_camera) || QDELETED(side_camera))
		Fail("Breaking a hull panel failed to drop only accessories mounted on that edge.")
	qdel(side_panel)
	if(!QDELETED(side_camera))
		Fail("Deleting a mounting wall left a live exterior camera.")
	var/obj/item/cargo = allocate(/obj/item, get_turf(jeep))
	var/obj/structure/chair/ms13_vehicle_seat/seat = locate() in get_turf(jeep)
	var/mob/living/carbon/human/consistent/driver = allocate(/mob/living/carbon/human/consistent, get_turf(jeep))
	seat.user_buckle_mob(driver, driver)
	var/turf/wreck = get_turf(jeep)
	jeep.deconstruct(FALSE)
	if(!QDELETED(engine) || vehicle.engine || !QDELETED(seat) || driver.buckled || cargo.loc != wreck || driver.loc != wreck)
		Fail("Destroyed frame retained supported hardware or lost its occupants/cargo.")
	for(var/obj/structure/ms13_vehicle_part/part as anything in vehicle.parts)
		if(part.forward_offset == 0 && part.right_offset == 0)
			Fail("Destroyed frame left an attached component in the controller.")
	if(!(locate(/obj/item/stack/sheet/ms13/scrap_steel) in wreck))
		Fail("Lost frame/hardware left no steel scrap.")
	clear_vehicle(vehicle)
	qdel(driver)
	qdel(cargo)

/// Mouths at both ends reproduce the old outboard-tip bug; already-parallel walls alone do not.
/datum/unit_test/ms13_rail_vehicles/proc/check_corridors(test_z)
	for(var/direction in GLOB.cardinals)
		var/obj/structure/ms13_vehicle_frame/m113/front_left/carrier = allocate(/obj/structure/ms13_vehicle_frame/m113/front_left, locate(30, 30, test_z))
		var/datum/ms13_ground_vehicle/vehicle = carrier.vehicle
		vehicle.driver = allocate(/mob/living/carbon/human/consistent, get_turf(carrier))
		if(direction != vehicle.dir && !vehicle.do_rotate(direction))
			Fail("Unable to orient corridor test vehicle.")
		var/list/borders = list()
		for(var/obj/structure/ms13_vehicle_frame/frame as anything in vehicle.frames)
			for(var/travel in list(direction, turn(direction, 180)))
				var/turf/next = get_step(frame, travel)
				if(vehicle.get_frame_at(next))
					continue
				for(var/side in list(turn(direction, 90), turn(direction, -90)))
					if(vehicle.get_frame_at(get_step(frame, side)))
						continue
					var/turf/border = get_step(next, side)
					border = border.ChangeTurf(/turf/closed/wall)
					borders[border] = border.get_integrity()
		vehicle.speed = 1
		for(var/travel in list(direction, turn(direction, 180), turn(direction, 180), direction))
			if(!vehicle.do_move(travel, TRUE))
				Fail("Three-wide M113 could not enter/reverse through an exact-width corridor ([direction]/[travel]).")
		for(var/turf/border as anything in borders)
			if(border.get_integrity() != borders[border])
				Fail("Vehicle damaged a wall outside its swept footprint.")
			border.ChangeTurf(/turf/open/floor/plating)
		clear_vehicle(vehicle)

/datum/unit_test/ms13_rail_vehicles/proc/measure_impact(mass, band, armor, test_z)
	var/obj/structure/ms13_vehicle_frame/frame = allocate(/obj/structure/ms13_vehicle_frame, locate(15, 15, test_z))
	var/datum/ms13_ground_vehicle/vehicle = new
	frame.vehicle = vehicle
	vehicle.pivot = frame
	vehicle.frames += frame
	vehicle.mass_per_frame = mass
	vehicle.speed = band
	frame.setArmor(getArmor(armor))
	var/obj/structure/obstacle = allocate(/obj/structure, locate(15, 14, test_z))
	obstacle.modify_max_integrity(100000)
	obstacle.setArmor(getArmor(0))
	var/integrity_before = obstacle.get_integrity()
	var/frame_before = frame.get_integrity()
	var/energy_before = vehicle.collision_energy()
	vehicle.damage_collision(obstacle, frame, SOUTH)
	. = list(integrity_before - obstacle.get_integrity(), frame_before - frame.get_integrity())
	if(vehicle.speed && vehicle.collision_energy() >= energy_before)
		Fail("A collision did not spend retained impact energy.")
	var/retained = vehicle.collision_energy()
	vehicle.damage_collision(obstacle, frame, SOUTH)
	if(vehicle.speed && vehicle.collision_energy() >= retained)
		Fail("Repeated collisions regenerated momentum without acceleration.")
	clear_vehicle(vehicle)
	qdel(obstacle)
#endif
