/datum/unit_test/ms13_shelf_placement
	name = "MS13 shelves: item clicks place on either half without damage"

/datum/unit_test/ms13_shelf_placement/Run()
	var/turf/site = get_step(run_loc_floor_bottom_left, NORTHEAST)
	var/mob/living/carbon/human/consistent/user = allocate(/mob/living/carbon/human/consistent, get_step(site, SOUTH))
	user.set_combat_mode(FALSE)
	for(var/shelf_type in list(/obj/structure/ms13/storage/large/shelf, /obj/structure/ms13/storage/large/shelf/wood/drawers))
		var/obj/structure/ms13/storage/large/shelf/shelf = allocate(shelf_type, site)
		var/obj/item/item = allocate(/obj/item, user)
		item.force = 30
		user.put_in_active_hand(item)
		var/integrity_before = shelf.get_integrity()
		item.melee_attack_chain(user, shelf, "icon-x=48;icon-y=48")
		if(get_turf(item) != get_step(site, EAST) || item.loc == user || item.pixel_x != 0 || item.pixel_y != 32 || shelf.get_integrity() != integrity_before)
			Fail("A normal item click did not place it at the clicked position on the shelf's far half.")
		user.put_in_active_hand(item)
		item.melee_attack_chain(user, shelf, "icon-x=8;icon-y=24")
		if(item.loc != site || item.pixel_x != -8 || item.pixel_y != 8)
			Fail("An item could not be picked up and replaced at another shelf position.")
		user.put_in_active_hand(item)
		ADD_TRAIT(item, TRAIT_NODROP, REF(src))
		item.melee_attack_chain(user, shelf, "icon-x=48;icon-y=48")
		if(item.loc != user || shelf.get_integrity() != integrity_before)
			Fail("A failed item transfer damaged the shelf or removed an undroppable item.")
		REMOVE_TRAIT(item, TRAIT_NODROP, REF(src))
		qdel(item)
		qdel(shelf)
	SSatoms.map_loader_begin(REF(src))
	var/obj/structure/ms13/storage/large/shelf/upright = new(site)
	upright.dir = EAST
	SSatoms.map_loader_stop(REF(src))
	SSatoms.InitializeAtoms(list(upright))
	allocated += upright
	var/obj/item/placed = allocate(/obj/item, user)
	user.put_in_active_hand(placed)
	placed.melee_attack_chain(user, upright, "icon-x=24;icon-y=48")
	if(placed.loc != get_step(site, NORTH) || placed.pixel_x != 8 || placed.pixel_y != 0)
		Fail("An east-facing shelf did not place its item on the clicked northern tile.")
