/datum/unit_test/ms13_mining
	name = "MS13 mining: deposits, timed work, stamina and supported tunnels"

/datum/unit_test/ms13_mining/Run()
	var/turf/origin = get_step(get_step(run_loc_floor_bottom_left, NORTH), EAST)
	var/turf/site = get_step(origin, EAST)
	var/original_type = site.type
	var/mob/living/carbon/human/miner = allocate(/mob/living/carbon/human/consistent, origin)
	var/obj/item/pickaxe/ms13/pick = allocate(/obj/item/pickaxe/ms13, origin)
	miner.put_in_hands(pick)
	miner.set_special_base(SPECIAL_STRENGTH, 2)
	var/weak_delay = miner.ms13_mining_delay(pick)
	miner.set_special_base(SPECIAL_STRENGTH, 10)
	if(miner.ms13_mining_delay(pick) >= weak_delay)
		Fail("Strength does not reduce mining time.")
	var/turf/closed/mineral/random/ms13/rock = site.ChangeTurf(/turf/closed/mineral/random/ms13/drought)
	if(rock.mineralType || rock.mining_health <= pick.mining_damage)
		Fail("MS13 rock still rolls SS13 ores or breaks in one swing.")
	rock.mining_health = pick.mining_damage // Two swings: progress must continue automatically.
	var/obj/structure/ms13/ore_deposit/other_deposit = allocate(/obj/structure/ms13/ore_deposit/iron, origin)
	var/old_integrity = other_deposit.get_integrity()
	INVOKE_ASYNC(miner, TYPE_PROC_REF(/mob/living, ms13_mine), rock, pick)
	sleep(0.2 SECONDS)
	if(!miner.ms13_mining || !DOING_INTERACTION(miner, "MINING_ORE"))
		Fail("Mining did not acquire its shared action lock.")
	if(miner.ms13_mine(other_deposit, pick) || other_deposit.get_integrity() != old_integrity)
		Fail("The miner worked a second deposit concurrently.")
	var/initial_stamina = miner.stamina.current
	sleep(2 * miner.ms13_mining_delay(pick) + 0.5 SECONDS)
	if(!isopenturf(site) || miner.ms13_mining)
		Fail("Mining did not automatically finish its second swing and release the lock.")
	if(miner.stamina.current >= initial_stamina || miner.stamina.regen_rate != initial(miner.stamina.regen_rate))
		Fail("Mining did not consume stamina or restore normal regeneration.")
	if(site.ms13_unsupported_span < 3 || site.ms13_unsupported_span > 5)
		Fail("New excavation did not receive a fixed randomized support spacing.")
	miner.stamina.current = 10
	if(miner.ms13_can_mine(other_deposit, pick))
		Fail("An exhausted miner can keep working.")
	miner.stamina.current = miner.stamina.maximum
	INVOKE_ASYNC(miner, TYPE_PROC_REF(/mob/living, ms13_mine), other_deposit, pick)
	sleep(0.2 SECONDS)
	miner.dropItemToGround(pick)
	sleep(0.3 SECONDS)
	if(miner.ms13_mining || other_deposit.get_integrity() != old_integrity)
		Fail("Putting away the pick did not interrupt mining cleanly.")
	qdel(other_deposit)
	site.ms13_unsupported_span = 0
	site = site.ChangeTurf(original_type)
	var/obj/structure/ms13/ore_deposit/gold/fixed_deposit = allocate(/obj/structure/ms13/ore_deposit/gold, site)
	fixed_deposit.enclosing_rock_type = /turf/closed/mineral/random/ms13/mammoth
	fixed_deposit.encase_in_rock()
	if(!istype(get_turf(fixed_deposit), /turf/closed/mineral/random/ms13/mammoth))
		Fail("A fixed deposit did not use its selected enclosing rock theme.")
	var/turf/closed/mineral/random/ms13/deposit_rock = get_turf(fixed_deposit)
	deposit_rock.MinedAway()
	if(!QDELETED(fixed_deposit) || !(locate(/obj/item/stack/sheet/ms13/nugget/nugget_gold) in site))
		Fail("Breaking the rock around a deposit didn't break the deposit into nuggets.")
	for(var/obj/item/stack/sheet/ms13/nugget/nugget in site)
		qdel(nugget)
	site = site.ChangeTurf(original_type)
	new /obj/structure/ms13/ore_deposit/random/high/drought(site)
	sleep(1)
	var/obj/structure/ms13/ore_deposit/rolled = locate() in site
	if(!istype(site, /turf/closed/mineral/random/ms13/drought) || (!istype(rolled, /obj/structure/ms13/ore_deposit/gold) && !istype(rolled, /obj/structure/ms13/ore_deposit/silver)))
		Fail("The high-value random deposit did not resolve to valuable ore in Drought rock.")
	qdel(rolled)
	site = site.ChangeTurf(original_type)
	// All test-room floor is excavated; no original entrance should support the center.
	var/list/floors = list()
	for(var/turf/open/floor in block(run_loc_floor_bottom_left, run_loc_floor_top_right))
		floors += floor
		floor.ms13_unsupported_span = 1
	var/obj/structure/ms13/cave_decor/support/beam = allocate(/obj/structure/ms13/cave_decor/support/beams, site)
	if(!site.ms13_roof_supported())
		Fail("An intact beam does not support its own tile.")
	qdel(beam)
	var/obj/structure/ms13/cave_decor/support/broken = allocate(/obj/structure/ms13/cave_decor/support/wall/broken, site)
	if(site.ms13_roof_supported())
		Fail("Broken beams still support the roof.")
	qdel(broken)
	beam = allocate(/obj/structure/ms13/cave_decor/support/beams, get_step(get_step(site, NORTH), NORTH))
	if(site.ms13_roof_supported())
		Fail("A beam outside the tile's support span still supports it.")
	site.ms13_unsupported_span = 3
	if(!site.ms13_roof_supported())
		Fail("A reachable beam inside the support span was missed.")
	qdel(beam)
	site.ms13_check_roof()
	if(!site.ms13_cave_in_pending)
		Fail("An unsupported tunnel did not warn of a cave-in.")
	beam = allocate(/obj/structure/ms13/cave_decor/support/beams, site)
	if(site.ms13_collapse_roof())
		Fail("Building a support during the warning did not prevent collapse.")
	qdel(beam)
	if(!site.ms13_collapse_roof() || !(locate(/obj/structure/ms13/cave_in) in site))
		Fail("An unsupported roof did not leave clearable rock debris.")
	for(var/turf/floor as anything in floors)
		floor.ms13_unsupported_span = 0
		floor.ms13_cave_in_pending = FALSE
