/datum/unit_test/ms13_wielding
	name = "MS13 wielding: both hands, toggle, HUD, sprites and recoil"

/datum/unit_test/ms13_wielding/Run()
	var/mob/living/carbon/human/person = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/gun/ballistic/automatic/ms13/semi/service/rifle = allocate(/obj/item/gun/ballistic/automatic/ms13/semi/service)
	var/old_force = rifle.force
	for(var/hand in 1 to 2)
		person.active_hand_index = hand
		person.last_wield_input = -1
		person.put_in_hand(rifle, hand)
		if(!person.wield_active_hand() || !rifle.wielded || !istype(person.get_inactive_held_item(), /obj/item/offhand))
			Fail("Wielding from hand [hand] did not reserve the opposite hand.")
		person.wield_active_hand() // The duplicate legacy V binding, during the same input tick.
		if(!rifle.wielded)
			Fail("The duplicate V binding immediately unwielded the gun.")
		var/mutable_appearance/held_icon = rifle.build_worn_icon(person, default_layer = HANDS_LAYER, default_icon_file = hand == 1 ? rifle.lefthand_file : rifle.righthand_file, isinhands = TRUE)
		if(held_icon.icon_state != "service_wielded")
			Fail("Wielding did not select the existing two-handed sprite.")
		person.last_wield_input = -1
		if(!person.wield_active_hand() || rifle.wielded || person.get_inactive_held_item() || rifle.force != old_force)
			Fail("Unwielding did not release the hand and restore force.")
		person.dropItemToGround(rifle)
	// Picking up into an inactive hand must not try to reserve the same occupied slot.
	person.active_hand_index = 1
	person.put_in_hand(rifle, 2)
	if(!rifle.wield(person) || !istype(person.get_item_for_held_index(1), /obj/item/offhand))
		Fail("Wielding an item in the inactive hand reserved the wrong slot.")
	var/obj/item/offhand/offhand = person.get_item_for_held_index(1)
	if(offhand.wield(person))
		Fail("The abstract offhand can itself be wielded.")
	person.dropItemToGround(rifle)
	if(rifle.wielded || person.get_num_held_items())
		Fail("Dropping a wielded item left an offhand or wielded state behind.")
	var/obj/item/pickaxe/ms13/pick = allocate(/obj/item/pickaxe/ms13)
	person.active_hand_index = 2
	person.put_in_hand(pick, 2)
	if(!pick.wield(person))
		Fail("A right-hand pickaxe cannot be wielded.")
	pick.unwield(person)
	var/obj/item/blocker = allocate(/obj/item, person.loc)
	person.put_in_hand(blocker, 1)
	if(pick.wield(person) || pick.wielded || person.get_item_for_held_index(1) != blocker)
		Fail("Wielding displaced an occupied offhand.")
	person.drop_all_held_items()
	var/obj/item/ms13/twohanded/fireaxe/axe = allocate(/obj/item/ms13/twohanded/fireaxe)
	person.put_in_active_hand(axe)
	axe.wield(person)
	if(axe.force != 45)
		Fail("Mojave wield metadata did not set the axe's specified force.")
	axe.unwield(person)
	if(axe.force != 15)
		Fail("Unwielding did not restore the axe's force.")
	person.drop_all_held_items()
	person.put_in_active_hand(rifle)
	rifle.wield(person)
	var/baseline_kick = rifle.shot_kick(person)
	person.set_special_base(SPECIAL_STRENGTH, 10)
	if(rifle.shot_kick(person) >= baseline_kick)
		Fail("Extra Strength does not steady a wielded rifle.")
	var/mob/living/carbon/human/armored = allocate(/mob/living/carbon/human/consistent)
	armored.equip_to_slot_if_possible(allocate(/obj/item/clothing/suit/space/hardsuit/ms13/power_armor), ITEM_SLOT_OCLOTHING, TRUE, TRUE, bypass_equip_delay_self = TRUE)
	if(rifle.shot_kick(armored) >= rifle.shot_kick(person))
		Fail("Power armor did not further steady the rifle.")
	var/obj/item/gun/ballistic/shotgun/ms13/shotgun = allocate(/obj/item/gun/ballistic/shotgun/ms13/lever)
	if(!shotgun.one_hand_by_weight || shotgun.unwielded_spread_bonus > 5 || shotgun.unwielded_recoil != shotgun.recoil)
		Fail("A Mojave shotgun retained SS13's fixed one-handed penalties.")
