// One small test covers the four skins plus the shared controller's spawn and expansion path.

/datum/unit_test/ms13_terrain_hiveminds
	name = "MOJAVE SUN: Terrain Hivemind Framework"

/datum/unit_test/ms13_terrain_hiveminds/Run()
	var/concrete_variants = 0
	for(var/hive_type in subtypesof(/datum/ms13_terrain_hivemind))
		var/datum/ms13_terrain_hivemind/network = new hive_type
		if(network.abstract)
			qdel(network)
			continue
		concrete_variants++
		TEST_ASSERT(network.terrain_icon && network.terrain_icon_state, "[network.name] has no terrain appearance.")
		TEST_ASSERT(network.core_icon && network.core_icon_state, "[network.name] has no core appearance.")
		TEST_ASSERT(network.wall_icon && network.wall_icon_state, "[network.name] has no wall appearance.")
		TEST_ASSERT(network.trap_icon && network.trap_icon_state, "[network.name] has no trap appearance.")
		TEST_ASSERT(network.turret_icon && network.turret_icon_state, "[network.name] has no turret appearance.")
		TEST_ASSERT(network.spawner_icon && network.spawner_icon_state, "[network.name] has no generator appearance.")
		TEST_ASSERT(network.converter_icon && network.converter_icon_state, "[network.name] has no corpse-converter appearance.")
		TEST_ASSERT(length(network.unit_appearances) >= 5, "[network.name] must define scout, footsoldier, ranged, heavy, and infector appearances.")
		var/list/unique_appearances = list()
		for(var/role in network.unit_appearances)
			var/list/unit_appearance = network.unit_appearances[role]
			TEST_ASSERT(islist(unit_appearance) && unit_appearance["name"] && unit_appearance["icon"] && unit_appearance["state"], "[network.name] has an incomplete [role] appearance.")
			var/unit_icon = unit_appearance["icon"]
			var/unit_icon_state = unit_appearance["state"]
			TEST_ASSERT(unit_icon_state in icon_states(unit_icon), "[network.name] has an invalid [role] icon state.")
			unique_appearances["[unit_icon]|[unit_icon_state]"] = TRUE
		TEST_ASSERT_EQUAL(length(unique_appearances), length(network.unit_appearances), "[network.name] reuses a sprite between two unit roles.")
		TEST_ASSERT(ispath(network.core_type, /obj/structure/ms13_hivemind/core), "[network.name] has an invalid core type.")
		TEST_ASSERT(ispath(network.terrain_type, /obj/structure/ms13_hivemind/terrain), "[network.name] has an invalid terrain type.")
		TEST_ASSERT(ispath(network.converter_mob_type, /mob/living/simple_animal/hostile/ms13/terrain_hivemind/converter), "[network.name] has an invalid converter unit type.")
		for(var/unit_type in network.mob_types + network.evolved_mob_types + network.elite_mob_types)
			TEST_ASSERT(ispath(unit_type, /mob/living/simple_animal/hostile/ms13/terrain_hivemind), "[network.name] has an invalid unit type.")
		if(network.terrain_smoothing_prefix)
			var/list/terrain_states = icon_states(network.terrain_icon)
			var/isolated_state = "[network.terrain_smoothing_prefix][network.terrain_smoothing_separator]0"
			var/connected_state = "[network.terrain_smoothing_prefix][network.terrain_smoothing_separator][network.terrain_smoothing_diagonals ? 255 : 15]"
			TEST_ASSERT(isolated_state in terrain_states, "[network.name] lacks its isolated smoothing state.")
			TEST_ASSERT(connected_state in terrain_states, "[network.name] lacks its fully connected smoothing state.")
		if(istype(network, /datum/ms13_terrain_hivemind/eris))
			TEST_ASSERT_EQUAL(network.terrain_icon_state, "wires", "Machine-hive terrain is using a disconnected quarter-tile wire state.")
			TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/suicide in network.evolved_mob_types, "The machine hive does not evolve its bomber unit.")
			TEST_ASSERT_EQUAL(network.unit_appearances["suicide"]["state"], "bomber", "The machine-hive bomber lacks its distinct sprite.")
		if(istype(network, /datum/ms13_terrain_hivemind/necromorph))
			TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/heavy/siege in network.elite_mob_types, "Necromorph evolution does not unlock its tripod.")
			TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/suicide/necromorph in network.elite_mob_types, "Necromorph evolution does not unlock its exploder.")
			TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/heavy/regenerator in network.elite_mob_types, "Necromorph evolution does not unlock its hunter.")
		if(istype(network, /datum/ms13_terrain_hivemind/xenomorph))
			TEST_ASSERT(network.converts_living_hosts && !network.converts_dead_hosts, "The xenomorph hive is not configured for living hosts.")
			TEST_ASSERT(network.captures_knocked_down_hosts, "The xenomorph hive still attacks knocked-down living hosts.")
			TEST_ASSERT(!network.converter_unit_enabled && !network.terrain_conversion_time, "Xenomorph hosts should incubate in nests rather than convert anywhere on weeds.")
			TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/hauler in network.evolved_mob_types, "The xenomorph hive does not evolve its carrier unit.")
			TEST_ASSERT(/obj/structure/ms13_hivemind/special/xenomorph_egg in network.special_types, "The xenomorph hive cannot grow its one-use facehugger egg.")
			TEST_ASSERT(network.can_cross_low_walls && network.can_haul_over_low_walls, "Xenomorphs cannot vault low walls while hauling hosts.")
			TEST_ASSERT_EQUAL(network.mob_off_terrain_damage, 0, "Xenomorphs lose health away from friendly terrain.")
			TEST_ASSERT_EQUAL(network.mob_orphan_damage, 0, "Xenomorphs lose health after their core is destroyed.")
		TEST_ASSERT(network.resource_per_tile > 0 && network.expansion_cost > 0 && network.special_cost > 0 && network.unit_cost > 0, "[network.name] has a broken resource economy.")
		TEST_ASSERT(network.structure_regeneration_rate > 0, "[network.name] does not regenerate damaged structures.")
		TEST_ASSERT(length(network.special_types) == 5, "[network.name] must expose walls, traps, turrets, unit generators, and corpse converters.")
		qdel(network)

	TEST_ASSERT_EQUAL(concrete_variants, 5, "The prototype should expose blob, flock, necromorph, Eris, and xenomorph variants.")

	var/turf/origin = locate(run_loc_floor_bottom_left.x + 3, run_loc_floor_bottom_left.y + 3, run_loc_floor_bottom_left.z)
	TEST_ASSERT(isopenturf(origin) && !origin.density, "The unit-test area has no open turf for a live hivemind check.")
	var/datum/ms13_terrain_hivemind/blob/live_network = new(origin, 20)
	TEST_ASSERT(live_network.core && !QDELETED(live_network.core), "Starting a concrete network did not create its core.")
	var/obj/projectile/ms13_hivemind/friendly_shot = new
	friendly_shot.source_network = live_network
	TEST_ASSERT(live_network.core.CanAllowThrough(friendly_shot, NORTH), "A hive projectile cannot pass through its own core.")
	var/obj/projectile/ms13_hivemind/unaffiliated_shot = new
	TEST_ASSERT(!live_network.core.CanAllowThrough(unaffiliated_shot, NORTH), "A foreign projectile incorrectly passes through a hive core.")
	qdel(friendly_shot)
	qdel(unaffiliated_shot)
	TEST_ASSERT(length(live_network.territory), "Starting a concrete network did not claim any nearby terrain.")
	var/old_territory_size = length(live_network.territory)
	live_network.resources = live_network.expansion_cost
	TEST_ASSERT(live_network.try_expand(), "A funded network with frontier tiles could not expand.")
	TEST_ASSERT_EQUAL(length(live_network.territory), old_territory_size + 1, "Expansion did not add exactly one terrain tile.")
	TEST_ASSERT_EQUAL(live_network.resources, 0, "Expansion did not spend its configured resource cost.")
	live_network.evolved_unit_threshold = length(live_network.territory)
	live_network.elite_unit_threshold = length(live_network.territory)
	var/list/unlocked_types = live_network.get_available_unit_types()
	TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/ranged in unlocked_types, "Growing territory did not unlock ranged units.")
	TEST_ASSERT(/mob/living/simple_animal/hostile/ms13/terrain_hivemind/heavy in unlocked_types, "Growing territory did not unlock heavy units.")

	var/obj/structure/ms13_hivemind/terrain/claimed_growth = live_network.territory[1]
	var/turf/claimed_turf = get_turf(claimed_growth)
	var/obj/structure/ms13_hivemind/special/wall/test_wall = new(claimed_turf, live_network)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/footsoldier/test_unit = new(claimed_turf, live_network)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/scout/test_scout = new(claimed_turf, live_network)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/ranged/test_ranged = new(claimed_turf, live_network)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/heavy/test_heavy = new(claimed_turf, live_network)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/converter/test_worker = new(claimed_turf, live_network)
	TEST_ASSERT(test_wall in live_network.specials, "Special structures do not register with their network.")
	TEST_ASSERT(!live_network.can_spawn_unit_at(claimed_turf), "Unit spawning ignores dense contents on a hive tile.")
	TEST_ASSERT(test_wall.CanAllowThrough(test_unit, NORTH), "A hive wall blocks a unit belonging to its own network.")
	var/obj/structure/low_wall/test_low_wall = new(claimed_turf)
	TEST_ASSERT(test_low_wall.CanAllowThrough(test_unit, NORTH), "Blob units cannot pass over a low wall.")
	TEST_ASSERT(test_unit in live_network.units, "Spawned units do not register with their network.")
	TEST_ASSERT(test_scout.roam_range > test_unit.roam_range && test_scout.move_to_delay < test_unit.move_to_delay, "Scouts are not configured to range farther and move faster than footsoldiers.")
	TEST_ASSERT(test_unit.environment_smash & ENVIRONMENT_SMASH_STRUCTURES, "Standard hive units cannot break structures which contain their patrols.")
	TEST_ASSERT(test_ranged.ranged && test_ranged.projectiletype == live_network.ranged_projectile_type && test_ranged.minimum_distance > 1, "Ranged units are not configured to keep distance and use their theme projectile.")
	TEST_ASSERT((test_heavy.environment_smash & ENVIRONMENT_SMASH_WALLS) && test_heavy.obj_damage > test_unit.obj_damage, "Heavy units cannot breach walls more effectively than footsoldiers.")
	TEST_ASSERT_EQUAL(test_heavy.off_terrain_damage_multiplier, 0, "Heavy units still decay while ranging beyond hive terrain.")
	TEST_ASSERT(test_worker.off_terrain_damage_multiplier > 0 && test_worker.off_terrain_damage_multiplier < 1, "Corpse workers do not have reduced off-terrain decay.")
	TEST_ASSERT(test_worker.corpse_converter, "The dedicated converter unit did not initialize as a corpse worker.")
	TEST_ASSERT(!test_worker.force_opens_doors && test_unit.force_opens_doors, "Door forcing is not limited to combat-capable hive units.")
	var/mob/living/simple_animal/chicken/test_corpse = new(claimed_turf)
	test_corpse.set_stat(DEAD)
	test_unit.find_local_corpses()
	TEST_ASSERT_EQUAL(live_network.find_reported_corpse(test_worker), test_corpse, "A worker could not retrieve a corpse reported by another network member.")
	TEST_ASSERT(live_network.claim_corpse(test_corpse, test_worker), "A reported corpse could not be reserved by a worker.")
	test_worker.corpse_target_ref = WEAKREF(test_corpse)
	TEST_ASSERT(test_worker.has_adjacent_conversion_target(), "An infector does not recognize an adjacent claimed corpse as active work.")
	var/old_unit_count = length(live_network.units)
	TEST_ASSERT(live_network.advance_corpse_conversion(test_corpse, test_worker, 1, 1), "A fully progressed corpse was not converted.")
	TEST_ASSERT_EQUAL(length(live_network.units), old_unit_count + 1, "Corpse conversion did not create exactly one network unit.")
	var/mob/living/simple_animal/chicken/stale_target_corpse = new(claimed_turf)
	stale_target_corpse.set_stat(DEAD)
	test_unit.GiveTarget(stale_target_corpse)
	TEST_ASSERT(test_unit.release_finished_target(), "A hive unit did not release a finished combat target for corpse work.")
	TEST_ASSERT(!test_unit.target, "A dead combat target remained assigned and stalled the hive AI.")
	qdel(stale_target_corpse)
	var/mob/living/simple_animal/chicken/failed_haul_corpse = new(claimed_turf)
	failed_haul_corpse.set_stat(DEAD)
	TEST_ASSERT(live_network.claim_corpse(failed_haul_corpse, test_unit), "The failed-haul test could not reserve its corpse.")
	test_unit.corpse_target_ref = WEAKREF(failed_haul_corpse)
	test_unit.clear_corpse_task(FALSE)
	TEST_ASSERT(!live_network.get_corpse_claim(failed_haul_corpse), "Abandoning a failed grab left its corpse permanently claimed.")
	qdel(failed_haul_corpse)
	var/mob/living/simple_animal/chicken/dead_worker_corpse = new(claimed_turf)
	dead_worker_corpse.set_stat(DEAD)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/converter/doomed_worker = new(claimed_turf, live_network)
	TEST_ASSERT(live_network.claim_corpse(dead_worker_corpse, doomed_worker), "The dead-worker test could not reserve its corpse.")
	doomed_worker.corpse_target_ref = WEAKREF(dead_worker_corpse)
	doomed_worker.death()
	TEST_ASSERT(!live_network.get_corpse_claim(dead_worker_corpse), "A dead corpse worker left its assignment permanently claimed.")
	qdel(dead_worker_corpse)
	qdel(doomed_worker)
	var/obj/structure/ms13_hivemind/special/converter/doomed_converter = new(claimed_turf, live_network)
	var/mob/living/simple_animal/chicken/converter_corpse_one = new(claimed_turf)
	var/mob/living/simple_animal/chicken/converter_corpse_two = new(claimed_turf)
	converter_corpse_one.set_stat(DEAD)
	converter_corpse_two.set_stat(DEAD)
	TEST_ASSERT(live_network.claim_corpse(converter_corpse_one, doomed_converter) && live_network.claim_corpse(converter_corpse_two, doomed_converter), "The destroyed-converter test could not reserve both corpses.")
	qdel(doomed_converter)
	TEST_ASSERT(!live_network.get_corpse_claim(converter_corpse_one) && !live_network.get_corpse_claim(converter_corpse_two), "A destroyed converter left queued corpses permanently claimed.")
	qdel(converter_corpse_one)
	qdel(converter_corpse_two)
	var/mob/living/simple_animal/chicken/recycled_corpse = new(claimed_turf)
	recycled_corpse.set_stat(DEAD)
	live_network.max_units = length(live_network.units)
	live_network.resources = 0
	TEST_ASSERT(live_network.advance_corpse_conversion(recycled_corpse, test_worker, 1, 1), "A completed corpse stalled at the unit cap instead of being recycled.")
	TEST_ASSERT_EQUAL(live_network.resources, live_network.corpse_recycling_value, "A corpse recycled at the unit cap did not return resources.")
	var/turf/vehicle_turf
	for(var/obj/structure/ms13_hivemind/terrain/growth as anything in live_network.territory)
		if(get_turf(growth) != claimed_turf)
			vehicle_turf = get_turf(growth)
			break
	TEST_ASSERT(vehicle_turf, "The live network has no second turf for vehicle-aware spawning and targeting checks.")
	var/datum/ms13_ground_vehicle/test_vehicle = new
	var/obj/structure/ms13_vehicle_frame/test_frame = new(vehicle_turf)
	test_frame.vehicle = test_vehicle
	test_vehicle.frames += test_frame
	TEST_ASSERT(!live_network.can_spawn_unit_at(vehicle_turf), "Hive units can spawn inside a ground vehicle footprint.")
	var/obj/structure/window/ms13_vehicle_wall/solid/light_wall = new(vehicle_turf)
	light_wall.parent_frame = test_frame
	test_vehicle.walls += light_wall
	TEST_ASSERT(test_unit.is_vehicle_hull_target(light_wall), "A light vehicle hull is not a valid hive target.")
	var/obj/structure/window/ms13_vehicle_wall/solid/civ96/tank/tank_wall = new(vehicle_turf)
	tank_wall.parent_frame = test_frame
	test_vehicle.walls += tank_wall
	var/obj/structure/window/ms13_vehicle_wall/solid/door/civ96/tank/tank_door = new(vehicle_turf)
	tank_door.parent_frame = test_frame
	test_vehicle.walls += tank_door
	TEST_ASSERT(!test_unit.is_vehicle_hull_target(light_wall), "A hive unit still targets arbitrary plating on a tank-grade vehicle.")
	TEST_ASSERT(test_unit.is_vehicle_hull_target(tank_door), "A hive unit does not prioritize the hatch on a tank-grade vehicle.")
	qdel(tank_door)
	qdel(tank_wall)
	qdel(light_wall)
	qdel(test_frame)
	qdel(test_vehicle)
	qdel(test_low_wall)
	qdel(test_wall)
	var/list/units_to_clean = live_network.units.Copy()
	var/list/growths_to_clean = live_network.territory.Copy()
	qdel(live_network)
	QDEL_LIST(units_to_clean)
	QDEL_LIST(growths_to_clean)

	var/datum/ms13_terrain_hivemind/necromorph/location_probe = new
	var/turf/hauling_origin
	for(var/turf/candidate in block(run_loc_floor_bottom_left, run_loc_floor_top_right))
		if(location_probe.can_claim(candidate))
			hauling_origin = candidate
			break
	qdel(location_probe)
	TEST_ASSERT(hauling_origin, "The unit-test area has no second claimable turf for corpse hauling.")
	var/datum/ms13_terrain_hivemind/necromorph/hauling_network = new(hauling_origin, 20)
	var/obj/structure/ms13_hivemind/terrain/hauling_growth = hauling_network.territory[1]
	var/turf/hauling_turf = get_turf(hauling_growth)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/footsoldier/hauler = new(hauling_turf, hauling_network)
	var/mob/living/simple_animal/chicken/hauled_corpse = new(hauling_turf)
	hauled_corpse.set_stat(DEAD)
	TEST_ASSERT(hauler.handle_corpse_work(), "A necromorph hauler did not accept a nearby corpse task.")
	TEST_ASSERT(hauler.is_grabbing(hauled_corpse), "The hauler did not physically grab its corpse.")
	TEST_ASSERT_EQUAL(hauling_network.get_corpse_claim(hauled_corpse), hauler, "The hauling unit lost its corpse claim before delivery.")
	TEST_ASSERT(hauler.handle_corpse_work(), "A necromorph hauler did not deliver its grabbed corpse.")
	TEST_ASSERT_EQUAL(hauling_network.get_corpse_claim(hauled_corpse), hauling_network.core, "The hauler did not deliver its corpse claim to the nearest nest.")
	TEST_ASSERT(!hauler.is_grabbing(hauled_corpse), "The hauler did not release the corpse at its nest.")
	var/old_hauling_unit_count = length(hauling_network.units)
	var/old_hauling_capacity = hauling_network.max_resources
	hauling_network.process_structure_corpse(hauling_network.core, hauling_network.structure_conversion_time)
	TEST_ASSERT_EQUAL(length(hauling_network.units), old_hauling_unit_count + 1, "The nest did not convert its delivered corpse into a unit.")
	TEST_ASSERT_EQUAL(hauling_network.max_resources, old_hauling_capacity + hauling_network.corpse_capacity_value, "A delivered corpse did not expand the hive's resource capacity.")
	var/list/hauling_units_to_clean = hauling_network.units.Copy()
	var/list/hauling_growths_to_clean = hauling_network.territory.Copy()
	qdel(hauling_network)
	QDEL_LIST(hauling_units_to_clean)
	QDEL_LIST(hauling_growths_to_clean)

	var/datum/ms13_terrain_hivemind/xenomorph/xeno_network = new(hauling_origin, 20)
	var/obj/structure/ms13_hivemind/terrain/xeno_growth = xeno_network.territory[1]
	var/turf/xeno_turf = get_turf(xeno_growth)
	var/mob/living/simple_animal/hostile/ms13/terrain_hivemind/hauler/xeno_carrier = new(xeno_turf, xeno_network)
	var/mob/living/simple_animal/chicken/living_host = new(xeno_turf)
	living_host.Paralyze(10 MINUTES, TRUE)
	TEST_ASSERT(xeno_network.is_convertible_corpse(living_host), "A disabled living host is not valid xenomorph feedstock.")
	TEST_ASSERT(!xeno_carrier.CanAttack(living_host), "A xenomorph carrier attacks a reservable living host instead of reporting it.")
	TEST_ASSERT(xeno_carrier.handle_corpse_work(), "A xenomorph carrier did not accept a living-host hauling task.")
	TEST_ASSERT(xeno_carrier.is_grabbing(living_host), "The xenomorph carrier did not physically grab its living host.")
	var/obj/structure/low_wall/xeno_low_wall = new(xeno_turf)
	TEST_ASSERT(xeno_low_wall.CanAllowThrough(living_host, NORTH), "A xenomorph carrier cannot drag its host over a low wall.")
	TEST_ASSERT(xeno_carrier.handle_corpse_work(), "The xenomorph carrier did not deliver its living host to a nest.")
	var/obj/structure/ms13_hivemind/xenomorph_nest/xeno_nest = locate() in get_turf(living_host)
	TEST_ASSERT(xeno_nest, "Delivering a living host on resin did not form a nest around it.")
	TEST_ASSERT_EQUAL(xeno_network.get_corpse_claim(living_host), xeno_nest, "The delivered living host was not reserved by its resin nest.")
	var/old_xeno_unit_count = length(xeno_network.units)
	xeno_nest.process(xeno_network.structure_conversion_time)
	TEST_ASSERT(!QDELETED(living_host), "A completed xenomorph incubation deleted its host instead of leaving a wounded body.")
	TEST_ASSERT_EQUAL(living_host.stat, DEAD, "A completed xenomorph incubation did not fatally wound its host; progress was [xeno_network.corpse_conversion_progress[WEAKREF(living_host)] || 0] and claimant was [xeno_network.get_corpse_claim(living_host)].")
	TEST_ASSERT(!xeno_network.is_convertible_corpse(living_host), "A xenomorph nest can incubate the same dead host twice.")
	TEST_ASSERT_EQUAL(length(xeno_network.units), old_xeno_unit_count + 1, "A completed living-host incubation did not birth one xenomorph.")
	qdel(living_host)
	qdel(xeno_low_wall)
	var/list/xeno_units_to_clean = xeno_network.units.Copy()
	var/list/xeno_growths_to_clean = xeno_network.territory.Copy()
	var/old_carrier_health = xeno_carrier.health
	qdel(xeno_network)
	xeno_carrier.process(1)
	TEST_ASSERT_EQUAL(xeno_carrier.health, old_carrier_health, "A xenomorph loses health after its core is destroyed.")
	QDEL_LIST(xeno_units_to_clean)
	QDEL_LIST(xeno_growths_to_clean)
