// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/mineral_door/wood/cdda/f_canvas_door
	name = "canvas door"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "f_canvas_door"

/obj/structure/mineral_door/wood/cdda/f_skin_door
	name = "skin door"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "f_skin_door"

/obj/structure/mineral_door/transparent/cdda/t_chaingate
	name = "chaingate"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_chaingate"

/obj/structure/mineral_door/transparent/cdda/t_chickenwire_gate
	name = "chickenwire gate"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_chickenwire_gate"

/obj/structure/mineral_door/wood/cdda/t_door
	name = "door"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door"

/obj/structure/mineral_door/transparent/cdda/t_door_curtain
	name = "door curtain"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_curtain"

/obj/structure/mineral_door/transparent/cdda/t_door_grass_curtain
	name = "door grass curtain"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_grass_curtain"

/obj/structure/mineral_door/iron/cdda/t_door_gray
	name = "door gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_gray"

/obj/structure/mineral_door/iron/cdda/t_door_green
	name = "door green"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_green"

/obj/structure/mineral_door/iron/cdda/t_door_lab
	name = "door lab"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_lab"

/obj/structure/mineral_door/wood/cdda/t_door_makeshift
	name = "door makeshift"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_makeshift"

/obj/structure/mineral_door/iron/cdda/t_door_metal
	name = "door metal"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_metal"

/obj/structure/mineral_door/iron/cdda/t_door_red
	name = "door red"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_red"

/obj/structure/mineral_door/iron/cdda/t_door_white
	name = "door white"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_door_white"

/obj/structure/mineral_door/iron/cdda/t_rdoor
	name = "rdoor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_rdoor"

/obj/structure/mineral_door/iron/cdda/t_retractable_gate
	name = "retractable gate"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_retractable_gate"

/obj/structure/mineral_door/transparent/cdda/t_splitrail_fencegate
	name = "splitrail fencegate"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/doors_mineral.dmi'
	icon_state = "t_splitrail_fencegate"
