// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/fence/vertical/cdda/t_bars
	name = "bars"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_bars"

/obj/structure/ms13/fence/vertical/cdda/t_bollard
	name = "bollard"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_bollard"

/obj/structure/ms13/fence/vertical/cdda/t_chainfence
	name = "chainfence"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_chainfence"

/obj/structure/ms13/fence/vertical/cdda/t_chainfence/north_south
	icon_state = "t_chainfence_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_chainfence/east_west
	icon_state = "t_chainfence_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_chainfence_posts
	name = "chainfence posts"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_chainfence_posts"

/obj/structure/ms13/fence/vertical/cdda/t_chickenwire_fence
	name = "chickenwire fence"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_chickenwire_fence"

/obj/structure/ms13/fence/vertical/cdda/t_chickenwire_fence/north_south
	icon_state = "t_chickenwire_fence_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_chickenwire_fence/east_west
	icon_state = "t_chickenwire_fence_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_chickenwire_fence_post
	name = "chickenwire fence post"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_chickenwire_fence_post"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_adobe_brick
	name = "embrasure adobe brick"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_adobe_brick"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_adobe_brick/north_south
	icon_state = "t_embrasure_adobe_brick_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_adobe_brick/east_west
	icon_state = "t_embrasure_adobe_brick_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_brick
	name = "embrasure brick"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_brick"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_brick/north_south
	icon_state = "t_embrasure_brick_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_brick/east_west
	icon_state = "t_embrasure_brick_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_log
	name = "embrasure log"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_log"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_log/north_south
	icon_state = "t_embrasure_log_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_log/east_west
	icon_state = "t_embrasure_log_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_rock
	name = "embrasure rock"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_rock"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_rock/north_south
	icon_state = "t_embrasure_rock_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_rock/east_west
	icon_state = "t_embrasure_rock_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_sconc
	name = "embrasure sconc"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_sconc"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_sconc/north_south
	icon_state = "t_embrasure_sconc_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_sconc/east_west
	icon_state = "t_embrasure_sconc_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_wood
	name = "embrasure wood"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_embrasure_wood"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_wood/north_south
	icon_state = "t_embrasure_wood_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_embrasure_wood/east_west
	icon_state = "t_embrasure_wood_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_fence_post
	name = "fence post"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_fence_post"

/obj/structure/ms13/fence/vertical/cdda/t_fence_rope
	name = "fence rope"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_fence_rope"

/obj/structure/ms13/fence/vertical/cdda/t_fence_rope/north_south
	icon_state = "t_fence_rope_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_fence_rope/east_west
	icon_state = "t_fence_rope_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_guardrail
	name = "guardrail"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_guardrail"

/obj/structure/ms13/fence/vertical/cdda/t_guardrail/north_south
	icon_state = "t_guardrail_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_guardrail/east_west
	icon_state = "t_guardrail_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_palisade
	name = "palisade"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_palisade"

/obj/structure/ms13/fence/vertical/cdda/t_palisade/north_south
	icon_state = "t_palisade_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_palisade/east_west
	icon_state = "t_palisade_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_palisade_embrasure
	name = "palisade embrasure"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_palisade_embrasure"

/obj/structure/ms13/fence/vertical/cdda/t_palisade_embrasure/north_south
	icon_state = "t_palisade_embrasure_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_palisade_embrasure/east_west
	icon_state = "t_palisade_embrasure_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_privacy_fence
	name = "privacy fence"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_privacy_fence"

/obj/structure/ms13/fence/vertical/cdda/t_privacy_fence/north_south
	icon_state = "t_privacy_fence_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_privacy_fence/east_west
	icon_state = "t_privacy_fence_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_railing
	name = "railing"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_railing"

/obj/structure/ms13/fence/vertical/cdda/t_railing/north_south
	icon_state = "t_railing_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_railing/east_west
	icon_state = "t_railing_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_splitrail_fence
	name = "splitrail fence"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_splitrail_fence"

/obj/structure/ms13/fence/vertical/cdda/t_splitrail_fence/north_south
	icon_state = "t_splitrail_fence_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_splitrail_fence/east_west
	icon_state = "t_splitrail_fence_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_wattle_fence
	name = "wattle fence"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_wattle_fence"

/obj/structure/ms13/fence/vertical/cdda/t_wattle_fence/north_south
	icon_state = "t_wattle_fence_north_south"

/obj/structure/ms13/fence/vertical/cdda/t_wattle_fence/east_west
	icon_state = "t_wattle_fence_east_west"

/obj/structure/ms13/fence/vertical/cdda/t_wattle_fence_posts
	name = "wattle fence posts"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/fences_layered.dmi'
	icon_state = "t_wattle_fence_posts"
