// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/turf/open/floor/plating/ms13/ground/cdda/t_brick_roof
	name = "brick roof"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_brick_roof"

/turf/open/floor/plating/ms13/ground/cdda/t_bridge
	name = "bridge"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_bridge"

/turf/open/floor/ms13/cdda/t_carpet_green
	name = "carpet green"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_carpet_green"

/turf/open/floor/ms13/cdda/t_carpet_purple
	name = "carpet purple"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_carpet_purple"

/turf/open/floor/ms13/cdda/t_carpet_red
	name = "carpet red"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_carpet_red"

/turf/open/floor/ms13/cdda/t_carpet_yellow
	name = "carpet yellow"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_carpet_yellow"

/turf/open/floor/plating/ms13/ground/cdda/t_concrete
	name = "concrete"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_concrete"

/turf/open/floor/plating/ms13/ground/cdda/t_deck_coating_no_roof
	name = "deck coating no roof"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_deck_coating_no_roof"

/turf/open/floor/plating/ms13/ground/cdda/t_deck_coating_no_roof_r
	name = "deck coating no roof r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_deck_coating_no_roof_r"

/turf/open/floor/plating/ms13/ground/cdda/t_deck_coating_no_roof_w
	name = "deck coating no roof w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_deck_coating_no_roof_w"

/turf/open/floor/plating/ms13/ground/cdda/t_deck_coating_no_roof_y
	name = "deck coating no roof y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_deck_coating_no_roof_y"

/turf/open/floor/ms13/cdda/t_floor
	name = "floor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor"

/turf/open/floor/ms13/cdda/t_floor_blue
	name = "floor blue"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_blue"

/turf/open/floor/ms13/cdda/t_floor_green
	name = "floor green"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_green"

/turf/open/floor/ms13/cdda/t_floor_primitive
	name = "floor primitive"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_primitive"

/turf/open/floor/ms13/cdda/t_floor_red
	name = "floor red"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_red"

/turf/open/floor/ms13/cdda/t_floor_resin
	name = "floor resin"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_resin"

/turf/open/floor/ms13/cdda/t_floor_wax
	name = "floor wax"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_wax"

/turf/open/floor/ms13/cdda/t_floor_waxed
	name = "floor waxed"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_waxed"

/turf/open/floor/ms13/cdda/t_floor_waxed_y
	name = "floor waxed y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_floor_waxed_y"

/turf/open/floor/plating/ms13/ground/cdda/t_glass_roof
	name = "glass roof"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_glass_roof"

/turf/open/floor/plating/ms13/ground/cdda/t_grate
	name = "grate"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_grate"

/turf/open/floor/ms13/cdda/t_linoleum_gray
	name = "linoleum gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_linoleum_gray"

/turf/open/floor/ms13/cdda/t_linoleum_white
	name = "linoleum white"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_linoleum_white"

/turf/open/floor/plating/ms13/ground/cdda/t_manhole
	name = "manhole"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_manhole"

/turf/open/floor/plating/ms13/ground/cdda/t_manhole_cover
	name = "manhole cover"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_manhole_cover"

/turf/open/floor/ms13/cdda/t_nl_catwalk
	name = "nl catwalk"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_nl_catwalk"

/turf/open/floor/ms13/cdda/t_paper
	name = "paper"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_paper"

/turf/open/floor/plating/ms13/ground/cdda/t_pontoon_dp
	name = "pontoon dp"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_pontoon_dp"

/turf/open/floor/plating/ms13/ground/cdda/t_railroad_rubble
	name = "railroad rubble"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_railroad_rubble"

/turf/open/floor/plating/ms13/ground/cdda/t_railroad_tie
	name = "railroad tie"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_railroad_tie"

/turf/open/floor/plating/ms13/ground/cdda/t_railroad_track
	name = "railroad track"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_railroad_track"

/turf/open/floor/plating/ms13/ground/cdda/t_railroad_track_on_tie
	name = "railroad track on tie"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_railroad_track_on_tie"

/turf/open/floor/plating/ms13/ground/cdda/t_railroad_track_small_d
	name = "railroad track small d"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_railroad_track_small_d"

/turf/open/floor/plating/ms13/ground/cdda/t_riverbridge_dp
	name = "riverbridge dp"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_riverbridge_dp"

/turf/open/floor/ms13/cdda/t_root_floor
	name = "root floor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_root_floor"

/turf/open/floor/ms13/cdda/t_scrap_floor
	name = "scrap floor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_scrap_floor"

/turf/open/floor/plating/ms13/ground/cdda/t_shingle_flat_roof
	name = "shingle flat roof"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_shingle_flat_roof"

/turf/open/floor/plating/ms13/ground/cdda/t_sidewalk
	name = "sidewalk"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_sidewalk"

/turf/open/floor/ms13/cdda/t_strconc_floor
	name = "strconc floor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_strconc_floor"

/turf/open/floor/ms13/cdda/t_wax
	name = "wax"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_wax"

/turf/open/floor/plating/ms13/ground/cdda/t_zebra
	name = "zebra"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/floors_layered.dmi'
	icon_state = "t_zebra"
