// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/flora/ms13/cdda/f_black_eyed_susan
	name = "black eyed susan"
	desc = "A black eyed susan."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_black_eyed_susan"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_bluebell
	name = "bluebell"
	desc = "A bluebell."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_bluebell_#0"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_burdock
	name = "burdock"
	desc = "A burdock."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_burdock"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_carrot_wild
	name = "carrot wild"
	desc = "A carrot wild."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_carrot_wild"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_chamomile
	name = "chamomile"
	desc = "A chamomile."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_chamomile"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_chicory
	name = "chicory"
	desc = "A chicory."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_chicory"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_dahlia
	name = "dahlia"
	desc = "A dahlia."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_dahlia_#0"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_dandelion
	name = "dandelion"
	desc = "A dandelion."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_dandelion_season_summer"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_datura
	name = "datura"
	desc = "A datura."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_datura"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_flower_fungal
	name = "flower fungal"
	desc = "A flower fungal."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_flower_fungal_#0"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_flower_spurge
	name = "flower spurge"
	desc = "A flower spurge."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_flower_spurge"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_flower_tulip
	name = "flower tulip"
	desc = "A flower tulip."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_flower_tulip_#0"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_indoor_plant
	name = "indoor plant"
	desc = "A indoor plant."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_indoor_plant"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_indoor_plant_y
	name = "indoor plant y"
	desc = "A indoor plant y."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_indoor_plant_y"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_lily
	name = "lily"
	desc = "A lily."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_lily"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_lilypad
	name = "lilypad"
	desc = "A lilypad."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_lilypad"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_lotus
	name = "lotus"
	desc = "A lotus."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_lotus"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_mustard
	name = "mustard"
	desc = "A mustard."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_mustard_season_summer"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_mutpoppy
	name = "mutpoppy"
	desc = "A mutpoppy."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_mutpoppy"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_plant_harvest
	name = "plant harvest"
	desc = "A plant harvest."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_plant_harvest"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_plant_mature
	name = "plant mature"
	desc = "A plant mature."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_plant_mature"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_plant_seed
	name = "plant seed"
	desc = "A plant seed."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_plant_seed"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_plant_seedling
	name = "plant seedling"
	desc = "A plant seedling."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_plant_seedling"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_planter
	name = "planter"
	desc = "A planter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_planter"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_planter_harvest
	name = "planter harvest"
	desc = "A planter harvest."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_planter_harvest"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_planter_mature
	name = "planter mature"
	desc = "A planter mature."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_planter_mature"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_planter_seedling
	name = "planter seedling"
	desc = "A planter seedling."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_planter_seedling"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_sunflower
	name = "sunflower"
	desc = "A sunflower."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "f_sunflower_season_spring"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_bamboo
	name = "bamboo"
	desc = "A bamboo."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_bamboo"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_bamboo_harvested
	name = "bamboo harvested"
	desc = "A bamboo harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_bamboo_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_bamboo_long
	name = "bamboo long"
	desc = "A bamboo long."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_bamboo_long"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_fern
	name = "fern"
	desc = "A fern."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_fern"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_fern_harvested
	name = "fern harvested"
	desc = "A fern harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_fern_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_marloss
	name = "marloss"
	desc = "A marloss."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_marloss"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub
	name = "shrub"
	desc = "A shrub."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_blackberry
	name = "shrub blackberry"
	desc = "A shrub blackberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_blackberry"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_blackberry_harvested
	name = "shrub blackberry harvested"
	desc = "A shrub blackberry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_blackberry_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_blueberry
	name = "shrub blueberry"
	desc = "A shrub blueberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_blueberry"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_blueberry_harvested
	name = "shrub blueberry harvested"
	desc = "A shrub blueberry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_blueberry_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_fungal
	name = "shrub fungal"
	desc = "A shrub fungal."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_fungal"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_grape
	name = "shrub grape"
	desc = "A shrub grape."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_grape"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_grape_harvested
	name = "shrub grape harvested"
	desc = "A shrub grape harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_grape_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_huckleberry
	name = "shrub huckleberry"
	desc = "A shrub huckleberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_huckleberry"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_huckleberry_harvested
	name = "shrub huckleberry harvested"
	desc = "A shrub huckleberry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_huckleberry_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_hydrangea
	name = "shrub hydrangea"
	desc = "A shrub hydrangea."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_hydrangea"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_hydrangea_harvested
	name = "shrub hydrangea harvested"
	desc = "A shrub hydrangea harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_hydrangea_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_lilac
	name = "shrub lilac"
	desc = "A shrub lilac."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_lilac"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_lilac_harvested
	name = "shrub lilac harvested"
	desc = "A shrub lilac harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_lilac_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_peanut
	name = "shrub peanut"
	desc = "A shrub peanut."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_peanut"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_peanut_harvested
	name = "shrub peanut harvested"
	desc = "A shrub peanut harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_peanut_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_raspberry
	name = "shrub raspberry"
	desc = "A shrub raspberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_raspberry"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_raspberry_harvested
	name = "shrub raspberry harvested"
	desc = "A shrub raspberry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_raspberry_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_rose
	name = "shrub rose"
	desc = "A shrub rose."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_rose"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_strawberry
	name = "shrub strawberry"
	desc = "A shrub strawberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_strawberry"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_shrub_strawberry_harvested
	name = "shrub strawberry harvested"
	desc = "A shrub strawberry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_shrub_strawberry_harvested"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_stump
	name = "stump"
	desc = "A stump."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_stump"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_triffid_leaves
	name = "triffid leaves"
	desc = "A triffid leaves."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_triffid_leaves"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_trunk
	name = "trunk"
	desc = "A trunk."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_trunk_#0"
	herbage = TRUE
	density = TRUE
	wood = TRUE

/obj/structure/flora/ms13/cdda/t_underbrush
	name = "underbrush"
	desc = "A underbrush."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_underbrush"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/t_underbrush_harvested_spring
	name = "underbrush harvested spring"
	desc = "A underbrush harvested spring."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora.dmi'
	icon_state = "t_underbrush_harvested_spring"
	herbage = TRUE

/obj/structure/flora/ms13/cdda/f_cattails
	name = "cattails"
	desc = "A cattails."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_32x64.dmi'
	icon_state = "f_cattails_season_summer"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/f_street_light
	name = "street light"
	desc = "A street light."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_32x64.dmi'
	icon_state = "f_street_light"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_bamboo_dead
	name = "bamboo dead"
	desc = "A bamboo dead."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_32x64.dmi'
	icon_state = "t_bamboo_dead"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_bamboo_tall
	name = "bamboo tall"
	desc = "A bamboo tall."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_32x64.dmi'
	icon_state = "t_bamboo_tall"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/tree/cdda/t_tree_fungal_young
	name = "tree fungal young"
	desc = "A tree fungal young."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_64x64.dmi'
	icon_state = "t_tree_fungal_young"

/obj/structure/flora/ms13/tree/cdda/t_tree_young
	name = "tree young"
	desc = "A tree young."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_64x64.dmi'
	icon_state = "t_tree_young"

/obj/structure/flora/ms13/cdda/t_marloss_tree
	name = "marloss tree"
	desc = "A marloss tree."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_marloss_tree"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree
	name = "tree"
	desc = "A tree."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_apple
	name = "tree apple"
	desc = "A tree apple."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_apple"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_apple_harvested
	name = "tree apple harvested"
	desc = "A tree apple harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_apple_harvested_#0"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_apricot
	name = "tree apricot"
	desc = "A tree apricot."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_apricot_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_beech
	name = "tree beech"
	desc = "A tree beech."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_beech"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_birch
	name = "tree birch"
	desc = "A tree birch."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_birch"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_birch_harvested
	name = "tree birch harvested"
	desc = "A tree birch harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_birch_harvested"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_burnt
	name = "tree burnt"
	desc = "A tree burnt."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_burnt"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_cherry
	name = "tree cherry"
	desc = "A tree cherry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_cherry"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_cherry_harvested
	name = "tree cherry harvested"
	desc = "A tree cherry harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_cherry_harvested"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_chestnut
	name = "tree chestnut"
	desc = "A tree chestnut."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_chestnut"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_coffee
	name = "tree coffee"
	desc = "A tree coffee."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_coffee"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_coffee_harvested
	name = "tree coffee harvested"
	desc = "A tree coffee harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_coffee_harvested"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_cottonwood
	name = "tree cottonwood"
	desc = "A tree cottonwood."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_cottonwood_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_cottonwood_harvested
	name = "tree cottonwood harvested"
	desc = "A tree cottonwood harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_cottonwood_harvested_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_dead
	name = "tree dead"
	desc = "A tree dead."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_dead_#1"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_deadpine
	name = "tree deadpine"
	desc = "A tree deadpine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_deadpine"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_elm
	name = "tree elm"
	desc = "A tree elm."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_elm_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_fungal
	name = "tree fungal"
	desc = "A tree fungal."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_fungal_#0"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_hickory
	name = "tree hickory"
	desc = "A tree hickory."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_hickory"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_maple
	name = "tree maple"
	desc = "A tree maple."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_maple"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_mulberry
	name = "tree mulberry"
	desc = "A tree mulberry."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_mulberry_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_peach
	name = "tree peach"
	desc = "A tree peach."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_peach_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_pear
	name = "tree pear"
	desc = "A tree pear."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_pear"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_pear_harvested
	name = "tree pear harvested"
	desc = "A tree pear harvested."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_pear_harvested"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_pine
	name = "tree pine"
	desc = "A tree pine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_pine"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_tree_plum
	name = "tree plum"
	desc = "A tree plum."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/flora_96x96.dmi'
	icon_state = "t_tree_plum_season_summer"
	herbage = TRUE
	density = TRUE
	wood = TRUE
	pixel_x = -32
	layer = 4.9
	plane = ABOVE_GAME_PLANE
