// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/cdda/f_archery_target_bale
	name = "archery target bale"
	desc = "A archery target bale."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_archery_target_bale"
	density = TRUE

/obj/structure/ms13/cdda/f_archery_target_box
	name = "archery target box"
	desc = "A archery target box."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_archery_target_box"
	density = TRUE

/obj/structure/ms13/cdda/f_armchair
	name = "armchair"
	desc = "A armchair."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_armchair_#0"
	density = TRUE

/obj/structure/ms13/cdda/f_barricade_road
	name = "barricade road"
	desc = "A barricade road."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_barricade_road"
	density = TRUE

/obj/structure/ms13/cdda/f_bathtub
	name = "bathtub"
	desc = "A bathtub."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bathtub"
	density = TRUE

/obj/structure/ms13/cdda/f_battlefield_cross
	name = "battlefield cross"
	desc = "A battlefield cross."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_battlefield_cross"
	density = TRUE

/obj/structure/ms13/cdda/f_bed
	name = "bed"
	desc = "A bed."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bed"
	density = TRUE

/obj/structure/ms13/cdda/f_bed_frame
	name = "bed frame"
	desc = "A bed frame."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bed_frame"
	density = TRUE

/obj/structure/ms13/cdda/f_bench
	name = "bench"
	desc = "A bench."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bench"
	density = TRUE

/obj/structure/ms13/cdda/f_bitts
	name = "bitts"
	desc = "A bitts."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bitts"
	density = TRUE

/obj/structure/ms13/cdda/f_brazier
	name = "brazier"
	desc = "A brazier."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_brazier"
	density = TRUE

/obj/structure/ms13/cdda/f_bulletin
	name = "bulletin"
	desc = "A bulletin."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bulletin"

/obj/structure/ms13/cdda/f_bullettrailer_bed_foot
	name = "bullettrailer bed foot"
	desc = "A bullettrailer bed foot."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_bed_foot"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_bed_head
	name = "bullettrailer bed head"
	desc = "A bullettrailer bed head."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_bed_head"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_minisofa
	name = "bullettrailer minisofa"
	desc = "A bullettrailer minisofa."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_minisofa"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_sign_danabakery
	name = "bullettrailer sign danabakery"
	desc = "A bullettrailer sign danabakery."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_sign_danabakery"

/obj/structure/ms13/cdda/f_bullettrailer_table_bottom
	name = "bullettrailer table bottom"
	desc = "A bullettrailer table bottom."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_table_bottom"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_table_middle
	name = "bullettrailer table middle"
	desc = "A bullettrailer table middle."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_table_middle"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_table_top
	name = "bullettrailer table top"
	desc = "A bullettrailer table top."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_table_top"
	density = TRUE

/obj/structure/ms13/cdda/f_bullettrailer_toilet
	name = "bullettrailer toilet"
	desc = "A bullettrailer toilet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_bullettrailer_toilet"
	density = TRUE

/obj/structure/ms13/cdda/f_camp_chair
	name = "camp chair"
	desc = "A camp chair."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_camp_chair"
	density = TRUE

/obj/structure/ms13/cdda/f_cardboard_box
	name = "cardboard box"
	desc = "A cardboard box."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_cardboard_box"
	density = TRUE

/obj/structure/ms13/cdda/f_chair
	name = "chair"
	desc = "A chair."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_chair_#0"
	density = TRUE

/obj/structure/ms13/cdda/f_chest
	name = "chest"
	desc = "A chest."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_chest"
	density = TRUE

/obj/structure/ms13/cdda/f_chimney
	name = "chimney"
	desc = "A chimney."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_chimney"
	density = TRUE

/obj/structure/ms13/cdda/f_counter
	name = "counter"
	desc = "A counter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_counter"
	density = TRUE

/obj/structure/ms13/cdda/f_cupboard
	name = "cupboard"
	desc = "A cupboard."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_cupboard"
	density = TRUE

/obj/structure/ms13/cdda/f_curtain
	name = "curtain"
	desc = "A curtain."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_curtain"

/obj/structure/ms13/cdda/f_curtain_open
	name = "curtain open"
	desc = "A curtain open."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_curtain_open"

/obj/structure/ms13/cdda/f_desk
	name = "desk"
	desc = "A desk."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_desk"
	density = TRUE

/obj/structure/ms13/cdda/f_displaycase
	name = "displaycase"
	desc = "A displaycase."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_displaycase"
	density = TRUE

/obj/structure/ms13/cdda/f_displaycase_b
	name = "displaycase b"
	desc = "A displaycase b."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_displaycase_b"
	density = TRUE

/obj/structure/ms13/cdda/f_dive_block
	name = "dive block"
	desc = "A dive block."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_dive_block"
	density = TRUE

/obj/structure/ms13/cdda/f_down_mattress
	name = "down mattress"
	desc = "A down mattress."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_down_mattress"

/obj/structure/ms13/cdda/f_earthbag_half
	name = "earthbag half"
	desc = "A earthbag half."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_earthbag_half"
	density = TRUE

/obj/structure/ms13/cdda/f_fiber_mat
	name = "fiber mat"
	desc = "A fiber mat."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_fiber_mat"

/obj/structure/ms13/cdda/f_filing_cabinet
	name = "filing cabinet"
	desc = "A filing cabinet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_filing_cabinet"
	density = TRUE

/obj/structure/ms13/cdda/f_floor_mattress
	name = "floor mattress"
	desc = "A floor mattress."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_floor_mattress"

/obj/structure/ms13/cdda/f_foot_locker
	name = "foot locker"
	desc = "A foot locker."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_foot_locker"
	density = TRUE

/obj/structure/ms13/cdda/f_grave_stone
	name = "grave stone"
	desc = "A grave stone."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_grave_stone_#0"
	density = TRUE

/obj/structure/ms13/cdda/f_grave_stone_old
	name = "grave stone old"
	desc = "A grave stone old."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_grave_stone_old_#0"
	density = TRUE

/obj/structure/ms13/cdda/f_groundsheet
	name = "groundsheet"
	desc = "A groundsheet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_groundsheet"

/obj/structure/ms13/cdda/f_intermodal_crate_open
	name = "intermodal crate open"
	desc = "A intermodal crate open."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_intermodal_crate_open"
	density = TRUE

/obj/structure/ms13/cdda/f_lane
	name = "lane"
	desc = "A lane."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_lane"

/obj/structure/ms13/cdda/f_leather_tarp
	name = "leather tarp"
	desc = "A leather tarp."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_leather_tarp"

/obj/structure/ms13/cdda/f_logstool
	name = "logstool"
	desc = "A logstool."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_logstool"
	density = TRUE

/obj/structure/ms13/cdda/f_magic_circle
	name = "magic circle"
	desc = "A magic circle."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_magic_circle"

/obj/structure/ms13/cdda/f_mailbox
	name = "mailbox"
	desc = "A mailbox."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_mailbox"
	density = TRUE

/obj/structure/ms13/cdda/f_makeshift_bed
	name = "makeshift bed"
	desc = "A makeshift bed."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_makeshift_bed"
	density = TRUE

/obj/structure/ms13/cdda/f_metal_bench
	name = "metal bench"
	desc = "A metal bench."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_metal_bench"
	density = TRUE

/obj/structure/ms13/cdda/f_metal_crate_c
	name = "metal crate c"
	desc = "A metal crate c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_metal_crate_c"
	density = TRUE

/obj/structure/ms13/cdda/f_metal_crate_o
	name = "metal crate o"
	desc = "A metal crate o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_metal_crate_o"
	density = TRUE

/obj/structure/ms13/cdda/f_metal_crate_r
	name = "metal crate r"
	desc = "A metal crate r."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_metal_crate_r"
	density = TRUE

/obj/structure/ms13/cdda/f_metal_table
	name = "metal table"
	desc = "A metal table."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_metal_table"
	density = TRUE

/obj/structure/ms13/cdda/f_pallet_belted
	name = "pallet belted"
	desc = "A pallet belted."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_pallet_belted"
	density = TRUE

/obj/structure/ms13/cdda/f_pallet_belted_open
	name = "pallet belted open"
	desc = "A pallet belted open."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_pallet_belted_open"
	density = TRUE

/obj/structure/ms13/cdda/f_piano
	name = "piano"
	desc = "A piano."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_piano"
	density = TRUE

/obj/structure/ms13/cdda/f_plastic_groundsheet
	name = "plastic groundsheet"
	desc = "A plastic groundsheet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_plastic_groundsheet"

/obj/structure/ms13/cdda/f_pool_table
	name = "pool table"
	desc = "A pool table."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_pool_table"
	density = TRUE

/obj/structure/ms13/cdda/f_rack
	name = "rack"
	desc = "A rack."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_rack"
	density = TRUE

/obj/structure/ms13/cdda/f_rack_wood
	name = "rack wood"
	desc = "A rack wood."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_rack_wood"
	density = TRUE

/obj/structure/ms13/cdda/f_recycle_bin
	name = "recycle bin"
	desc = "A recycle bin."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_recycle_bin"
	density = TRUE

/obj/structure/ms13/cdda/f_safe_c
	name = "safe c"
	desc = "A safe c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_safe_c"
	density = TRUE

/obj/structure/ms13/cdda/f_safe_o
	name = "safe o"
	desc = "A safe o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_safe_o"
	density = TRUE

/obj/structure/ms13/cdda/f_sandbag_half
	name = "sandbag half"
	desc = "A sandbag half."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sandbag_half"
	density = TRUE

/obj/structure/ms13/cdda/f_scrap_bridge
	name = "scrap bridge"
	desc = "A scrap bridge."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_scrap_bridge"
	density = TRUE

/obj/structure/ms13/cdda/f_screenmirror
	name = "screenmirror"
	desc = "A screenmirror."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_screenmirror"
	density = TRUE

/obj/structure/ms13/cdda/f_sealed_intermodal_crate
	name = "sealed intermodal crate"
	desc = "A sealed intermodal crate."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sealed_intermodal_crate"
	density = TRUE

/obj/structure/ms13/cdda/f_seat_airplane
	name = "seat airplane"
	desc = "A seat airplane."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_seat_airplane"

/obj/structure/ms13/cdda/f_sign
	name = "sign"
	desc = "A sign."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sign"

/obj/structure/ms13/cdda/f_sign_warning
	name = "sign warning"
	desc = "A sign warning."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sign_warning"

/obj/structure/ms13/cdda/f_sink
	name = "sink"
	desc = "A sink."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sink"
	density = TRUE

/obj/structure/ms13/cdda/f_skin_groundsheet
	name = "skin groundsheet"
	desc = "A skin groundsheet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_skin_groundsheet"

/obj/structure/ms13/cdda/f_slab
	name = "slab"
	desc = "A slab."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_slab"
	density = TRUE

/obj/structure/ms13/cdda/f_sofa
	name = "sofa"
	desc = "A sofa."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_sofa"
	density = TRUE

/obj/structure/ms13/cdda/f_stool
	name = "stool"
	desc = "A stool."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_stool"
	density = TRUE

/obj/structure/ms13/cdda/f_straw_bed
	name = "straw bed"
	desc = "A straw bed."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_straw_bed"

/obj/structure/ms13/cdda/f_table
	name = "table"
	desc = "A table."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_table"
	density = TRUE

/obj/structure/ms13/cdda/f_tatami
	name = "tatami"
	desc = "A tatami."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_tatami_#0"

/obj/structure/ms13/cdda/f_toilet
	name = "toilet"
	desc = "A toilet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_toilet"
	density = TRUE

/obj/structure/ms13/cdda/f_tourist_table
	name = "tourist table"
	desc = "A tourist table."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_tourist_table"
	density = TRUE

/obj/structure/ms13/cdda/f_trashcan
	name = "trashcan"
	desc = "A trashcan."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_trashcan"
	density = TRUE

/obj/structure/ms13/cdda/f_vent_pipe
	name = "vent pipe"
	desc = "A vent pipe."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_vent_pipe"
	density = TRUE

/obj/structure/ms13/cdda/f_wind_vane
	name = "wind vane"
	desc = "A wind vane."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture.dmi'
	icon_state = "f_wind_vane"
	density = TRUE

/obj/structure/ms13/cdda/f_coffin_c
	name = "coffin c"
	desc = "A coffin c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_coffin_c"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_coffin_o
	name = "coffin o"
	desc = "A coffin o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_coffin_o"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dancing_pole
	name = "dancing pole"
	desc = "A dancing pole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_dancing_pole"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_eyewash
	name = "eyewash"
	desc = "A eyewash."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_eyewash"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_fireman_cabinet
	name = "fireman cabinet"
	desc = "A fireman cabinet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_fireman_cabinet"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_fireman_cabinet_b
	name = "fireman cabinet b"
	desc = "A fireman cabinet b."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_fireman_cabinet_b"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hammock
	name = "hammock"
	desc = "A hammock."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hammock"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hammock_net
	name = "hammock net"
	desc = "A hammock net."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hammock_net"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hanging_meathook
	name = "hanging meathook"
	desc = "A hanging meathook."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hanging_meathook"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hoist_chain
	name = "hoist chain"
	desc = "A hoist chain."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hoist_chain"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hoist_pulley
	name = "hoist pulley"
	desc = "A hoist pulley."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hoist_pulley"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hoist_rope
	name = "hoist rope"
	desc = "A hoist rope."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hoist_rope"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_huge_mana_crystal
	name = "huge mana crystal"
	desc = "A huge mana crystal."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_huge_mana_crystal"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_hydraulic_press
	name = "hydraulic press"
	desc = "A hydraulic press."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_hydraulic_press"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_orrery
	name = "orrery"
	desc = "A orrery."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_orrery"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_rope_up
	name = "rope up"
	desc = "A rope up."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_rope_up"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_winter_wreath
	name = "winter wreath"
	desc = "A winter wreath."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x48.dmi'
	icon_state = "f_winter_wreath"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_IV_pole
	name = "IV pole"
	desc = "A IV pole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_IV_pole"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_aluminum_stepladder
	name = "aluminum stepladder"
	desc = "A aluminum stepladder."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_aluminum_stepladder"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bigmirror
	name = "bigmirror"
	desc = "A bigmirror."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bigmirror"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bigmirror_b
	name = "bigmirror b"
	desc = "A bigmirror b."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bigmirror_b"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_birdbath
	name = "birdbath"
	desc = "A birdbath."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_birdbath"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bookcase
	name = "bookcase"
	desc = "A bookcase."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bookcase"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bullettrailer_cabinet
	name = "bullettrailer cabinet"
	desc = "A bullettrailer cabinet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bullettrailer_cabinet"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bullettrailer_desk
	name = "bullettrailer desk"
	desc = "A bullettrailer desk."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bullettrailer_desk"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_bullettrailer_sink
	name = "bullettrailer sink"
	desc = "A bullettrailer sink."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_bullettrailer_sink"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_canvas_floor
	name = "canvas floor"
	desc = "A canvas floor."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_canvas_floor"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_crate_c
	name = "crate c"
	desc = "A crate c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_crate_c"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_crate_o
	name = "crate o"
	desc = "A crate o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_crate_o"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_deckchair
	name = "deckchair"
	desc = "A deckchair."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_deckchair_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dresser
	name = "dresser"
	desc = "A dresser."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_dresser_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dumpster
	name = "dumpster"
	desc = "A dumpster."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_dumpster"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exercise
	name = "exercise"
	desc = "A exercise."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_exercise"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_fireplace
	name = "fireplace"
	desc = "A fireplace."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_fireplace"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_flagpole
	name = "flagpole"
	desc = "A flagpole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_flagpole"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_floor_lamp
	name = "floor lamp"
	desc = "A floor lamp."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_floor_lamp"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_glass_cabinet
	name = "glass cabinet"
	desc = "A glass cabinet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_glass_cabinet"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_ladder
	name = "ladder"
	desc = "A ladder."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_ladder"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_locker
	name = "locker"
	desc = "A locker."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_locker"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_mannequin
	name = "mannequin"
	desc = "A mannequin."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_mannequin"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_pallet_brick
	name = "pallet brick"
	desc = "A pallet brick."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_pallet_brick"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_pallet_brick_adobe
	name = "pallet brick adobe"
	desc = "A pallet brick adobe."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_pallet_brick_adobe"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_pallet_cement
	name = "pallet cement"
	desc = "A pallet cement."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_pallet_cement"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_punching_bag
	name = "punching bag"
	desc = "A punching bag."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_punching_bag"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_rack_coat
	name = "rack coat"
	desc = "A rack coat."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_rack_coat"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_shower
	name = "shower"
	desc = "A shower."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_shower"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_sign_stop
	name = "sign stop"
	desc = "A sign stop."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_sign_stop"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_stack_plank
	name = "stack plank"
	desc = "A stack plank."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_stack_plank"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_statue
	name = "statue"
	desc = "A statue."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_statue"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_training_dummy_heavy
	name = "training dummy heavy"
	desc = "A training dummy heavy."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_training_dummy_heavy"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_training_dummy_light
	name = "training dummy light"
	desc = "A training dummy light."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_training_dummy_light"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_utility_pole
	name = "utility pole"
	desc = "A utility pole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_utility_pole"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_wardrobe
	name = "wardrobe"
	desc = "A wardrobe."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_wardrobe"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_wooden_flagpole
	name = "wooden flagpole"
	desc = "A wooden flagpole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_wooden_flagpole"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_woodstove
	name = "woodstove"
	desc = "A woodstove."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_32x64.dmi'
	icon_state = "f_woodstove"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_LIXA_electrical_conduit
	name = "LIXA electrical conduit"
	desc = "A LIXA electrical conduit."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_LIXA_electrical_conduit"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_electrical_conduit
	name = "electrical conduit"
	desc = "A electrical conduit."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_electrical_conduit"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_fireman_cabinet_o
	name = "fireman cabinet o"
	desc = "A fireman cabinet o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_fireman_cabinet_o"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_gun_safe_el
	name = "gun safe el"
	desc = "A gun safe el."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_gun_safe_el"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_gunsafe_mj
	name = "gunsafe mj"
	desc = "A gunsafe mj."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_gunsafe_mj"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_gunsafe_ml
	name = "gunsafe ml"
	desc = "A gunsafe ml."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_gunsafe_ml"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_gunsafe_o
	name = "gunsafe o"
	desc = "A gunsafe o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_gunsafe_o"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_pillow_fort
	name = "pillow fort"
	desc = "A pillow fort."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_pillow_fort"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_rotary_clothesline
	name = "rotary clothesline"
	desc = "A rotary clothesline."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_rotary_clothesline"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_stook_empty
	name = "stook empty"
	desc = "A stook empty."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_stook_empty"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_stook_full
	name = "stook full"
	desc = "A stook full."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/furniture_64x64.dmi'
	icon_state = "f_stook_full"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE
