// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/turf/open/floor/plating/ms13/ground/cdda/t_clay
	name = "clay"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_clay"

/turf/open/floor/plating/ms13/ground/cdda/t_claymound
	name = "claymound"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_claymound"

/turf/open/floor/plating/ms13/ground/cdda/t_deaddirt
	name = "deaddirt"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_deaddirt_#0"

/turf/open/floor/plating/ms13/ground/cdda/t_dirt
	name = "dirt"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_dirt"

/turf/open/floor/plating/ms13/ground/cdda/t_dirtfloor
	name = "dirtfloor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_dirtfloor"

/turf/open/floor/plating/ms13/ground/cdda/t_dirtmound
	name = "dirtmound"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_dirtmound"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus
	name = "fungus"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_corner_ne
	name = "fungus4 corner ne"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_corner_ne"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_corner_nw
	name = "fungus4 corner nw"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_corner_nw"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_corner_se
	name = "fungus4 corner se"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_corner_se"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_corner_sw
	name = "fungus4 corner sw"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_corner_sw"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_edge_ew
	name = "fungus4 edge ew"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_edge_ew"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_edge_ns
	name = "fungus4 edge ns"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_edge_ns"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_end_piece_e
	name = "fungus4 end piece e"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_end_piece_e"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_end_piece_n
	name = "fungus4 end piece n"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_end_piece_n"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_end_piece_s
	name = "fungus4 end piece s"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_end_piece_s"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_end_piece_w
	name = "fungus4 end piece w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_end_piece_w"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_t_connection_e
	name = "fungus4 t connection e"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_t_connection_e"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_t_connection_n
	name = "fungus4 t connection n"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_t_connection_n"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_t_connection_s
	name = "fungus4 t connection s"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_t_connection_s"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus4_t_connection_w
	name = "fungus4 t connection w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus4_t_connection_w"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus_floor_in
	name = "fungus floor in"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus_floor_in"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus_mound
	name = "fungus mound"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus_mound"

/turf/open/floor/plating/ms13/ground/cdda/t_fungus_sticks16
	name = "fungus sticks16"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_fungus_sticks16"

/turf/open/floor/plating/ms13/ground/cdda/t_grass
	name = "grass"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_grass_#0"

/turf/open/floor/plating/ms13/ground/cdda/t_grass_dead
	name = "grass dead"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_grass_dead"

/turf/open/floor/plating/ms13/ground/cdda/t_grass_white
	name = "grass white"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_grass_white"

/turf/open/floor/plating/ms13/ground/cdda/t_ice
	name = "ice"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_ice"

/turf/open/floor/plating/ms13/ground/cdda/t_lake_bed
	name = "lake bed"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_lake_bed"

/turf/open/floor/plating/ms13/ground/cdda/t_lava
	name = "lava"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_lava"

/turf/open/floor/plating/ms13/ground/cdda/t_moss
	name = "moss"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_moss"

/turf/open/floor/plating/ms13/ground/cdda/t_mud
	name = "mud"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_mud"

/turf/open/floor/plating/ms13/ground/cdda/t_nl_chasm
	name = "nl chasm"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_nl_chasm"

/turf/open/floor/plating/ms13/ground/cdda/t_open_air
	name = "open air"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_open_air"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_corpsed
	name = "pit corpsed"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_corpsed"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_covered
	name = "pit covered"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_covered"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_glass
	name = "pit glass"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_glass"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_glass_covered
	name = "pit glass covered"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_glass_covered"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_shallow
	name = "pit shallow"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_shallow"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_spiked
	name = "pit spiked"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_spiked"

/turf/open/floor/plating/ms13/ground/cdda/t_pit_spiked_covered
	name = "pit spiked covered"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_pit_spiked_covered"

/turf/open/floor/plating/ms13/ground/cdda/t_puddle
	name = "puddle"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_puddle"

/turf/open/floor/plating/ms13/ground/cdda/t_puddle_underground
	name = "puddle underground"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_puddle_underground"

/turf/open/floor/plating/ms13/ground/cdda/t_rock
	name = "rock"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_rock"

/turf/open/floor/plating/ms13/ground/cdda/t_rock_blue
	name = "rock blue"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_rock_blue"

/turf/open/floor/plating/ms13/ground/cdda/t_rock_floor
	name = "rock floor"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_rock_floor"

/turf/open/floor/plating/ms13/ground/cdda/t_rock_green
	name = "rock green"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_rock_green"

/turf/open/floor/plating/ms13/ground/cdda/t_rock_red
	name = "rock red"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_rock_red"

/turf/open/floor/plating/ms13/ground/cdda/t_sand
	name = "sand"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_sand"

/turf/open/floor/plating/ms13/ground/cdda/t_sandbox
	name = "sandbox"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_sandbox"

/turf/open/floor/plating/ms13/ground/cdda/t_sandmound
	name = "sandmound"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_sandmound_season_spring"

/turf/open/floor/plating/ms13/ground/cdda/t_searth_test
	name = "searth test"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_searth_test"

/turf/open/floor/plating/ms13/ground/cdda/t_snow
	name = "snow"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_snow"

/turf/open/floor/plating/ms13/ground/cdda/t_soil
	name = "soil"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_soil"

/turf/open/floor/plating/ms13/ground/cdda/t_water_dp
	name = "water dp"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_water_dp"

/turf/open/floor/plating/ms13/ground/cdda/t_water_hot
	name = "water hot"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_water_hot"

/turf/open/floor/plating/ms13/ground/cdda/t_water_moving_dp
	name = "water moving dp"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_water_moving_dp"

/turf/open/floor/plating/ms13/ground/cdda/t_water_moving_sh
	name = "water moving sh"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_water_moving_sh"

/turf/open/floor/plating/ms13/ground/cdda/t_water_pool
	name = "water pool"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_water_pool"

/turf/open/floor/plating/ms13/ground/cdda/t_woodchips
	name = "woodchips"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground.dmi'
	icon_state = "t_woodchips"
