// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/cdda/f_anvil
	name = "anvil"
	desc = "A anvil."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_anvil"
	density = TRUE

/obj/structure/ms13/cdda/f_bandsaw
	name = "bandsaw"
	desc = "A bandsaw."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_bandsaw"
	density = TRUE

/obj/structure/ms13/cdda/f_beverly_shear
	name = "beverly shear"
	desc = "A beverly shear."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_beverly_shear"
	density = TRUE

/obj/structure/ms13/cdda/f_clay_kiln
	name = "clay kiln"
	desc = "A clay kiln."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_clay_kiln"
	density = TRUE

/obj/structure/ms13/cdda/f_jointer
	name = "jointer"
	desc = "A jointer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_jointer"
	density = TRUE

/obj/structure/ms13/cdda/f_kiln_empty
	name = "kiln empty"
	desc = "A kiln empty."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_kiln_empty"
	density = TRUE

/obj/structure/ms13/cdda/f_manual_tire_changer
	name = "manual tire changer"
	desc = "A manual tire changer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_manual_tire_changer"
	density = TRUE

/obj/structure/ms13/cdda/f_mitresaw
	name = "mitresaw"
	desc = "A mitresaw."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_mitresaw"
	density = TRUE

/obj/structure/ms13/cdda/f_planer
	name = "planer"
	desc = "A planer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_planer"

/obj/structure/ms13/cdda/f_scutch_breaker
	name = "scutch breaker"
	desc = "A scutch breaker."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_scutch_breaker"
	density = TRUE

/obj/structure/ms13/cdda/f_tablesaw
	name = "tablesaw"
	desc = "A tablesaw."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools.dmi'
	icon_state = "f_tablesaw"
	density = TRUE

/obj/structure/ms13/cdda/f_drill_press
	name = "drill press"
	desc = "A drill press."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_32x48.dmi'
	icon_state = "f_drill_press"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_magic_bench
	name = "magic bench"
	desc = "A magic bench."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_32x64.dmi'
	icon_state = "f_magic_bench"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_workbench
	name = "workbench"
	desc = "A workbench."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_32x64.dmi'
	icon_state = "f_workbench"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_butcher_rack
	name = "butcher rack"
	desc = "A butcher rack."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_butcher_rack"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_smoking_rack
	name = "smoking rack"
	desc = "A smoking rack."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_smoking_rack"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_smoking_rack_active
	name = "smoking rack active"
	desc = "A smoking rack active."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_smoking_rack_active"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_spinwheel
	name = "spinwheel"
	desc = "A spinwheel."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_spinwheel"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_spinwheel_cordage
	name = "spinwheel cordage"
	desc = "A spinwheel cordage."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_spinwheel_cordage"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_spinwheel_leather
	name = "spinwheel leather"
	desc = "A spinwheel leather."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/large_tools_64x64.dmi'
	icon_state = "f_spinwheel_leather"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE
