// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/cdda/f_alembic
	name = "alembic"
	desc = "A alembic."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage.dmi'
	icon_state = "f_alembic"
	density = TRUE

/obj/structure/ms13/cdda/f_water_purifier
	name = "water purifier"
	desc = "A water purifier."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage.dmi'
	icon_state = "f_water_purifier"
	density = TRUE

/obj/structure/ms13/cdda/f_wood_keg
	name = "wood keg"
	desc = "A wood keg."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage.dmi'
	icon_state = "f_wood_keg"
	density = TRUE

/obj/structure/ms13/cdda/f_fvat_empty
	name = "fvat empty"
	desc = "A fvat empty."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage_32x64.dmi'
	icon_state = "f_fvat_empty"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_standing_tank
	name = "standing tank"
	desc = "A standing tank."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage_32x64.dmi'
	icon_state = "f_standing_tank"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_water_heater
	name = "water heater"
	desc = "A water heater."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage_32x64.dmi'
	icon_state = "f_water_heater"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_water_pump
	name = "water pump"
	desc = "A water pump."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/liquid_storage_32x64.dmi'
	icon_state = "f_water_pump"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE
