// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/cdda/f_TV_antenna
	name = "TV antenna"
	desc = "A TV antenna."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_TV_antenna"
	density = TRUE

/obj/structure/ms13/cdda/f_active_backup_generator
	name = "active backup generator"
	desc = "A active backup generator."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_active_backup_generator"
	density = TRUE

/obj/structure/ms13/cdda/f_air_conditioner
	name = "air conditioner"
	desc = "A air conditioner."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_air_conditioner"
	density = TRUE

/obj/structure/ms13/cdda/f_autoclave
	name = "autoclave"
	desc = "A autoclave."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_autoclave"
	density = TRUE

/obj/structure/ms13/cdda/f_cellphone_booster
	name = "cellphone booster"
	desc = "A cellphone booster."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_cellphone_booster"
	density = TRUE

/obj/structure/ms13/cdda/f_centrifuge
	name = "centrifuge"
	desc = "A centrifuge."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_centrifuge"
	density = TRUE

/obj/structure/ms13/cdda/f_compact_ASRG_containment
	name = "compact ASRG containment"
	desc = "A compact ASRG containment."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_compact_ASRG_containment"
	density = TRUE

/obj/structure/ms13/cdda/f_exodii_pump
	name = "exodii pump"
	desc = "A exodii pump."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_exodii_pump"
	density = TRUE

/obj/structure/ms13/cdda/f_freezer
	name = "freezer"
	desc = "A freezer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_freezer"
	density = TRUE

/obj/structure/ms13/cdda/f_generator_broken
	name = "generator broken"
	desc = "A generator broken."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_generator_broken"
	density = TRUE

/obj/structure/ms13/cdda/f_hd_compressor_unit
	name = "hd compressor unit"
	desc = "A hd compressor unit."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_hd_compressor_unit"
	density = TRUE

/obj/structure/ms13/cdda/f_oxygen_concentrator
	name = "oxygen concentrator"
	desc = "A oxygen concentrator."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_oxygen_concentrator"
	density = TRUE

/obj/structure/ms13/cdda/f_pinball_machine
	name = "pinball machine"
	desc = "A pinball machine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_pinball_machine"
	density = TRUE

/obj/structure/ms13/cdda/f_roof_turbine_vent
	name = "roof turbine vent"
	desc = "A roof turbine vent."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_roof_turbine_vent"
	density = TRUE

/obj/structure/ms13/cdda/f_shredder
	name = "shredder"
	desc = "A shredder."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_shredder"
	density = TRUE

/obj/structure/ms13/cdda/f_small_satelitte_dish
	name = "small satelitte dish"
	desc = "A small satelitte dish."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_small_satelitte_dish"
	density = TRUE

/obj/structure/ms13/cdda/f_small_satellite_dish
	name = "small satellite dish"
	desc = "A small satellite dish."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_small_satellite_dish"
	density = TRUE

/obj/structure/ms13/cdda/f_solar_unit
	name = "solar unit"
	desc = "A solar unit."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_solar_unit"
	density = TRUE

/obj/structure/ms13/cdda/f_speaker_cabinet
	name = "speaker cabinet"
	desc = "A speaker cabinet."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_speaker_cabinet"
	density = TRUE

/obj/structure/ms13/cdda/f_water_mill
	name = "water mill"
	desc = "A water mill."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery.dmi'
	icon_state = "f_water_mill"
	density = TRUE

/obj/structure/ms13/cdda/f_clay_oven
	name = "clay oven"
	desc = "A clay oven."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x48.dmi'
	icon_state = "f_clay_oven"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_LIXA_machinery_electronic
	name = "LIXA machinery electronic"
	desc = "A LIXA machinery electronic."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_LIXA_machinery_electronic_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_arcade_machine
	name = "arcade machine"
	desc = "A arcade machine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_arcade_machine"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_autodoc_couch
	name = "autodoc couch"
	desc = "A autodoc couch."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_autodoc_couch"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_capacitor
	name = "capacitor"
	desc = "A capacitor."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_capacitor"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_console
	name = "console"
	desc = "A console."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_console"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_console_broken
	name = "console broken"
	desc = "A console broken."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_console_broken"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dialysis
	name = "dialysis"
	desc = "A dialysis."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_dialysis"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dishwasher
	name = "dishwasher"
	desc = "A dishwasher."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_dishwasher"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_dryer
	name = "dryer"
	desc = "A dryer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_dryer"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_ergometer
	name = "ergometer"
	desc = "A ergometer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_ergometer"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_charger
	name = "exodii charger"
	desc = "A exodii charger."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_charger"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_charger_cheap
	name = "exodii charger cheap"
	desc = "A exodii charger cheap."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_charger_cheap"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_lamp
	name = "exodii lamp"
	desc = "A exodii lamp."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_lamp"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_lamp_string_warped
	name = "exodii lamp string warped"
	desc = "A exodii lamp string warped."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_lamp_string_warped"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_portal_tower
	name = "exodii portal tower"
	desc = "A exodii portal tower."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_portal_tower"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_printer_large
	name = "exodii printer large"
	desc = "A exodii printer large."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_printer_large"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_printer_small
	name = "exodii printer small"
	desc = "A exodii printer small."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_printer_small"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_scanner
	name = "exodii scanner"
	desc = "A exodii scanner."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_exodii_scanner"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_fridge
	name = "fridge"
	desc = "A fridge."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_fridge_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_glass_fridge
	name = "glass fridge"
	desc = "A glass fridge."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_glass_fridge"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_home_furnace
	name = "home furnace"
	desc = "A home furnace."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_home_furnace"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_machinery_electronic
	name = "machinery electronic"
	desc = "A machinery electronic."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_machinery_electronic"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_machinery_heavy
	name = "machinery heavy"
	desc = "A machinery heavy."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_machinery_heavy_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_machinery_light
	name = "machinery light"
	desc = "A machinery light."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_machinery_light_#0"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_machinery_old
	name = "machinery old"
	desc = "A machinery old."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_machinery_old"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_nl_exodii_lamp
	name = "nl exodii lamp"
	desc = "A nl exodii lamp."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_nl_exodii_lamp"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_oven
	name = "oven"
	desc = "A oven."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_oven_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_scan_bed
	name = "scan bed"
	desc = "A scan bed."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_scan_bed"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_scrap_antenna
	name = "scrap antenna"
	desc = "A scrap antenna."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_scrap_antenna_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_traffic_light
	name = "traffic light"
	desc = "A traffic light."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_traffic_light"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_treadmill
	name = "treadmill"
	desc = "A treadmill."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_treadmill"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_vending_c
	name = "vending c"
	desc = "A vending c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_vending_c"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_vending_o
	name = "vending o"
	desc = "A vending o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_vending_o"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_vending_reinforced
	name = "vending reinforced"
	desc = "A vending reinforced."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_vending_reinforced"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_ventilator
	name = "ventilator"
	desc = "A ventilator."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_ventilator"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_washer
	name = "washer"
	desc = "A washer."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_washer"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_wind_mill
	name = "wind mill"
	desc = "A wind mill."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_32x64.dmi'
	icon_state = "f_wind_mill"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_CTscan
	name = "CTscan"
	desc = "A CTscan."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_CTscan"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_MRI
	name = "MRI"
	desc = "A MRI."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_MRI"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_generator_1
	name = "exodii generator 1"
	desc = "A exodii generator 1."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_exodii_generator_1"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_generator_2
	name = "exodii generator 2"
	desc = "A exodii generator 2."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_exodii_generator_2"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_generator_3
	name = "exodii generator 3"
	desc = "A exodii generator 3."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_exodii_generator_3"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_exodii_generator_4
	name = "exodii generator 4"
	desc = "A exodii generator 4."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/machinery_64x64.dmi'
	icon_state = "f_exodii_generator_4"
	density = TRUE
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE
