// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/ms13/cdda/f_30gal_firebarrel_fd_fire
	name = "30gal firebarrel fd fire"
	desc = "A 30gal firebarrel fd fire."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_30gal_firebarrel_fd_fire_#0"

/obj/structure/ms13/cdda/f_55gal_firebarrel_fd_fire
	name = "55gal firebarrel fd fire"
	desc = "A 55gal firebarrel fd fire."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_55gal_firebarrel_fd_fire_#0"

/obj/structure/ms13/cdda/f_absence
	name = "absence"
	desc = "A absence."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_absence"

/obj/structure/ms13/cdda/f_alien_anemone
	name = "alien anemone"
	desc = "A alien anemone."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_alien_anemone"

/obj/structure/ms13/cdda/f_alien_table
	name = "alien table"
	desc = "A alien table."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_alien_table"
	density = TRUE

/obj/structure/ms13/cdda/f_ash
	name = "ash"
	desc = "A ash."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_ash"

/obj/structure/ms13/cdda/f_boulder_medium
	name = "boulder medium"
	desc = "A boulder medium."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_boulder_medium"
	density = TRUE

/obj/structure/ms13/cdda/f_boulder_small
	name = "boulder small"
	desc = "A boulder small."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_boulder_small"
	density = TRUE

/obj/structure/ms13/cdda/f_egg_sackbw
	name = "egg sackbw"
	desc = "A egg sackbw."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_egg_sackbw"

/obj/structure/ms13/cdda/f_egg_sackcs
	name = "egg sackcs"
	desc = "A egg sackcs."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_egg_sackcs"

/obj/structure/ms13/cdda/f_egg_sacke
	name = "egg sacke"
	desc = "A egg sacke."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_egg_sacke"

/obj/structure/ms13/cdda/f_egg_sackws
	name = "egg sackws"
	desc = "A egg sackws."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_egg_sackws"

/obj/structure/ms13/cdda/f_firering
	name = "firering"
	desc = "A firering."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_firering"

/obj/structure/ms13/cdda/f_fungal_clump
	name = "fungal clump"
	desc = "A fungal clump."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_fungal_clump"

/obj/structure/ms13/cdda/f_fungal_mass
	name = "fungal mass"
	desc = "A fungal mass."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_fungal_mass"

/obj/structure/ms13/cdda/f_fungal_tangle
	name = "fungal tangle"
	desc = "A fungal tangle."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_fungal_tangle"

/obj/structure/ms13/cdda/f_leaves_pile
	name = "leaves pile"
	desc = "A leaves pile."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_leaves_pile"

/obj/structure/ms13/cdda/f_rubble
	name = "rubble"
	desc = "A rubble."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_rubble"

/obj/structure/ms13/cdda/f_rubble_landfill
	name = "rubble landfill"
	desc = "A rubble landfill."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_rubble_landfill"

/obj/structure/ms13/cdda/f_rubble_rock
	name = "rubble rock"
	desc = "A rubble rock."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_rubble_rock"

/obj/structure/ms13/cdda/f_sand_castle
	name = "sand castle"
	desc = "A sand castle."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_sand_castle"

/obj/structure/ms13/cdda/f_woodchips
	name = "woodchips"
	desc = "A woodchips."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_woodchips"

/obj/structure/ms13/cdda/f_wreckage
	name = "wreckage"
	desc = "A wreckage."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "f_wreckage"
	density = TRUE

/obj/structure/ms13/cdda/t_LIXA_laser
	name = "LIXA laser"
	desc = "A LIXA laser."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_LIXA_laser"
	density = TRUE

/obj/structure/ms13/cdda/t_LIXA_tube
	name = "LIXA tube"
	desc = "A LIXA tube."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_LIXA_tube"
	density = TRUE

/obj/structure/ms13/cdda/t_LIXA_unfolded_tube
	name = "LIXA unfolded tube"
	desc = "A LIXA unfolded tube."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_LIXA_unfolded_tube"
	density = TRUE

/obj/structure/ms13/cdda/t_LIXA_unfolded_tube_broken
	name = "LIXA unfolded tube broken"
	desc = "A LIXA unfolded tube broken."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_LIXA_unfolded_tube_broken"
	density = TRUE

/obj/structure/ms13/cdda/t_broken_prefab
	name = "broken prefab"
	desc = "A broken prefab."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_broken_prefab_#0"
	density = TRUE

/obj/structure/ms13/cdda/t_buffer_stop
	name = "buffer stop"
	desc = "A buffer stop."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_buffer_stop"

/obj/structure/ms13/cdda/t_bullettrailer_inner_T
	name = "bullettrailer inner T"
	desc = "A bullettrailer inner T."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_bullettrailer_inner_T"

/obj/structure/ms13/cdda/t_card_artisans
	name = "card artisans"
	desc = "A card artisans."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_artisans"

/obj/structure/ms13/cdda/t_card_fp
	name = "card fp"
	desc = "A card fp."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_fp"

/obj/structure/ms13/cdda/t_card_industrial
	name = "card industrial"
	desc = "A card industrial."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_industrial"

/obj/structure/ms13/cdda/t_card_military
	name = "card military"
	desc = "A card military."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_military"

/obj/structure/ms13/cdda/t_card_reader_broken
	name = "card reader broken"
	desc = "A card reader broken."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_reader_broken"

/obj/structure/ms13/cdda/t_card_science
	name = "card science"
	desc = "A card science."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science"

/obj/structure/ms13/cdda/t_card_science_maintenance_blue
	name = "card science maintenance blue"
	desc = "A card science maintenance blue."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_maintenance_blue"

/obj/structure/ms13/cdda/t_card_science_maintenance_green
	name = "card science maintenance green"
	desc = "A card science maintenance green."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_maintenance_green"

/obj/structure/ms13/cdda/t_card_science_maintenance_yellow
	name = "card science maintenance yellow"
	desc = "A card science maintenance yellow."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_maintenance_yellow"

/obj/structure/ms13/cdda/t_card_science_medical_red
	name = "card science medical red"
	desc = "A card science medical red."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_medical_red"

/obj/structure/ms13/cdda/t_card_science_mutagen_cyan
	name = "card science mutagen cyan"
	desc = "A card science mutagen cyan."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_mutagen_cyan"

/obj/structure/ms13/cdda/t_card_science_mutagen_green
	name = "card science mutagen green"
	desc = "A card science mutagen green."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_mutagen_green"

/obj/structure/ms13/cdda/t_card_science_mutagen_pink
	name = "card science mutagen pink"
	desc = "A card science mutagen pink."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_mutagen_pink"

/obj/structure/ms13/cdda/t_card_science_security_black
	name = "card science security black"
	desc = "A card science security black."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_security_black"

/obj/structure/ms13/cdda/t_card_science_security_magenta
	name = "card science security magenta"
	desc = "A card science security magenta."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_security_magenta"

/obj/structure/ms13/cdda/t_card_science_security_yellow
	name = "card science security yellow"
	desc = "A card science security yellow."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_security_yellow"

/obj/structure/ms13/cdda/t_card_science_transport_1
	name = "card science transport 1"
	desc = "A card science transport 1."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_card_science_transport_1"

/obj/structure/ms13/cdda/t_console
	name = "console"
	desc = "A console."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_console"
	density = TRUE

/obj/structure/ms13/cdda/t_console_broken
	name = "console broken"
	desc = "A console broken."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_console_broken"
	density = TRUE

/obj/structure/ms13/cdda/t_conveyor
	name = "conveyor"
	desc = "A conveyor."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_conveyor"

/obj/structure/ms13/cdda/t_covered_well
	name = "covered well"
	desc = "A covered well."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_covered_well"

/obj/structure/ms13/cdda/t_current_trans
	name = "current trans"
	desc = "A current trans."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_current_trans"

/obj/structure/ms13/cdda/t_golf_hole
	name = "golf hole"
	desc = "A golf hole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_golf_hole"

/obj/structure/ms13/cdda/t_gutter
	name = "gutter"
	desc = "A gutter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_gutter"

/obj/structure/ms13/cdda/t_gutter_drop
	name = "gutter drop"
	desc = "A gutter drop."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_gutter_drop"

/obj/structure/ms13/cdda/t_intercom
	name = "intercom"
	desc = "A intercom."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_intercom"

/obj/structure/ms13/cdda/t_intermodal_crate
	name = "intermodal crate"
	desc = "A intermodal crate."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_intermodal_crate"
	density = TRUE

/obj/structure/ms13/cdda/t_m_frame
	name = "m frame"
	desc = "A m frame."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_m_frame"
	density = TRUE

/obj/structure/ms13/cdda/t_metal_ventilation_shutter
	name = "metal ventilation shutter"
	desc = "A metal ventilation shutter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_metal_ventilation_shutter"

/obj/structure/ms13/cdda/t_nm_brain
	name = "nm brain"
	desc = "A nm brain."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_nm_brain"
	density = TRUE

/obj/structure/ms13/cdda/t_nm_ichor_sh
	name = "nm ichor sh"
	desc = "A nm ichor sh."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_nm_ichor_sh"

/obj/structure/ms13/cdda/t_ov_reb_cage
	name = "ov reb cage"
	desc = "A ov reb cage."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_ov_reb_cage"
	density = TRUE

/obj/structure/ms13/cdda/t_ov_smreb_cage
	name = "ov smreb cage"
	desc = "A ov smreb cage."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_ov_smreb_cage"
	density = TRUE

/obj/structure/ms13/cdda/t_pedestal_temple
	name = "pedestal temple"
	desc = "A pedestal temple."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_pedestal_temple_#0"
	density = TRUE

/obj/structure/ms13/cdda/t_pedestal_wyrm
	name = "pedestal wyrm"
	desc = "A pedestal wyrm."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_pedestal_wyrm"
	density = TRUE

/obj/structure/ms13/cdda/t_potential_trans
	name = "potential trans"
	desc = "A potential trans."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_potential_trans"

/obj/structure/ms13/cdda/t_reb_cage
	name = "reb cage"
	desc = "A reb cage."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_reb_cage"
	density = TRUE

/obj/structure/ms13/cdda/t_reinforced_glass
	name = "reinforced glass"
	desc = "A reinforced glass."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_reinforced_glass"

/obj/structure/ms13/cdda/t_reinforced_glass_shutter
	name = "reinforced glass shutter"
	desc = "A reinforced glass shutter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_reinforced_glass_shutter"

/obj/structure/ms13/cdda/t_reinforced_glass_shutter_open
	name = "reinforced glass shutter open"
	desc = "A reinforced glass shutter open."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_reinforced_glass_shutter_open"

/obj/structure/ms13/cdda/t_resin_hole
	name = "resin hole"
	desc = "A resin hole."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_resin_hole"

/obj/structure/ms13/cdda/t_resin_hole_c
	name = "resin hole c"
	desc = "A resin hole c."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_resin_hole_c"

/obj/structure/ms13/cdda/t_resin_hole_o
	name = "resin hole o"
	desc = "A resin hole o."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_resin_hole_o"

/obj/structure/ms13/cdda/t_rootcellar
	name = "rootcellar"
	desc = "A rootcellar."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_rootcellar"

/obj/structure/ms13/cdda/t_sewage_pipe
	name = "sewage pipe"
	desc = "A sewage pipe."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_sewage_pipe"

/obj/structure/ms13/cdda/t_skylight_frame
	name = "skylight frame"
	desc = "A skylight frame."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_skylight_frame"

/obj/structure/ms13/cdda/t_slide
	name = "slide"
	desc = "A slide."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_slide"

/obj/structure/ms13/cdda/t_slot_machine
	name = "slot machine"
	desc = "A slot machine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_slot_machine"
	density = TRUE

/obj/structure/ms13/cdda/t_switch_even
	name = "switch even"
	desc = "A switch even."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_switch_even"

/obj/structure/ms13/cdda/t_switch_gb
	name = "switch gb"
	desc = "A switch gb."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_switch_gb"

/obj/structure/ms13/cdda/t_switch_rb
	name = "switch rb"
	desc = "A switch rb."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_switch_rb"

/obj/structure/ms13/cdda/t_switch_rg
	name = "switch rg"
	desc = "A switch rg."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_switch_rg"

/obj/structure/ms13/cdda/t_ticket_machine
	name = "ticket machine"
	desc = "A ticket machine."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc.dmi'
	icon_state = "t_ticket_machine"
	density = TRUE

/obj/structure/ms13/cdda/t_apiary
	name = "apiary"
	desc = "A apiary."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x48.dmi'
	icon_state = "t_apiary"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_apiary_empty
	name = "apiary empty"
	desc = "A apiary empty."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x48.dmi'
	icon_state = "t_apiary_empty"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_alien_gasper
	name = "alien gasper"
	desc = "A alien gasper."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_alien_gasper"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_alien_pod
	name = "alien pod"
	desc = "A alien pod."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_alien_pod"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_alien_pod_resin
	name = "alien pod resin"
	desc = "A alien pod resin."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_alien_pod_resin"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_alien_tendril
	name = "alien tendril"
	desc = "A alien tendril."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_alien_tendril"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_alien_zapper
	name = "alien zapper"
	desc = "A alien zapper."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_alien_zapper"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_boulder_large
	name = "boulder large"
	desc = "A boulder large."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_boulder_large"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_glow_boulder
	name = "glow boulder"
	desc = "A glow boulder."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_glow_boulder"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/f_ground_cable
	name = "ground cable"
	desc = "A ground cable."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "f_ground_cable"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_LIXA_portal_pulse
	name = "LIXA portal pulse"
	desc = "A LIXA portal pulse."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_LIXA_portal_pulse_#0"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_LIXA_unfolded_portal_pulse
	name = "LIXA unfolded portal pulse"
	desc = "A LIXA unfolded portal pulse."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_LIXA_unfolded_portal_pulse"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_atm
	name = "atm"
	desc = "A atm."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_atm"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_backboard
	name = "backboard"
	desc = "A backboard."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_backboard"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_gas_pump
	name = "gas pump"
	desc = "A gas pump."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_gas_pump"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_gutter_downspout
	name = "gutter downspout"
	desc = "A gutter downspout."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_gutter_downspout"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_lgtn_arrest
	name = "lgtn arrest"
	desc = "A lgtn arrest."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_lgtn_arrest"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_0
	name = "nl obelisk 0"
	desc = "A nl obelisk 0."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_nl_obelisk_0"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_1
	name = "nl obelisk 1"
	desc = "A nl obelisk 1."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_nl_obelisk_1"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_2
	name = "nl obelisk 2"
	desc = "A nl obelisk 2."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_nl_obelisk_2"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_3
	name = "nl obelisk 3"
	desc = "A nl obelisk 3."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_nl_obelisk_3"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_mission_boiler
	name = "nl obelisk mission boiler"
	desc = "A nl obelisk mission boiler."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_nl_obelisk_mission_boiler"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_oil_circ_brkr_s
	name = "oil circ brkr s"
	desc = "A oil circ brkr s."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_oil_circ_brkr_s"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_radio_tower
	name = "radio tower"
	desc = "A radio tower."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_radio_tower"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_sai_box
	name = "sai box"
	desc = "A sai box."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_sai_box"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_sai_box_damaged
	name = "sai box damaged"
	desc = "A sai box damaged."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_sai_box_damaged"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_ticket_vendor
	name = "ticket vendor"
	desc = "A ticket vendor."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_ticket_vendor"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_utility_light
	name = "utility light"
	desc = "A utility light."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_32x64.dmi'
	icon_state = "t_utility_light"
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_improvised_shelter
	name = "improvised shelter"
	desc = "A improvised shelter."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_improvised_shelter"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_improvised_shelter_filled
	name = "improvised shelter filled"
	desc = "A improvised shelter filled."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_improvised_shelter_filled"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_oil_circ_brkr_l
	name = "oil circ brkr l"
	desc = "A oil circ brkr l."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_oil_circ_brkr_l"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_tarptent
	name = "tarptent"
	desc = "A tarptent."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_tarptent"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_vat
	name = "vat"
	desc = "A vat."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_vat"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_webbed_corpse
	name = "webbed corpse"
	desc = "A webbed corpse."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_webbed_corpse"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_wooden_well
	name = "wooden well"
	desc = "A wooden well."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/terrain_misc_64x64.dmi'
	icon_state = "t_wooden_well"
	pixel_x = -16
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_grass_alien
	name = "grass alien"
	desc = "A grass alien."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground_32x64.dmi'
	icon_state = "t_grass_alien"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_grass_long
	name = "grass long"
	desc = "A grass long."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground_32x64.dmi'
	icon_state = "t_grass_long"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/flora/ms13/cdda/t_grass_tall
	name = "grass tall"
	desc = "A grass tall."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground_32x64.dmi'
	icon_state = "t_grass_tall"
	herbage = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_obelisk_mission_water_cooler
	name = "nl obelisk mission water cooler"
	desc = "A nl obelisk mission water cooler."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground_32x64.dmi'
	icon_state = "t_nl_obelisk_mission_water_cooler"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE

/obj/structure/ms13/cdda/t_nl_water_cooler
	name = "nl water cooler"
	desc = "A nl water cooler."
	icon = 'mojave/icons/cdda_ultimate_cataclysm/ground_32x64.dmi'
	icon_state = "t_nl_water_cooler"
	density = TRUE
	layer = 4.9
	plane = ABOVE_GAME_PLANE
