// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/turf/closed/wall/ms13/concrete/cdda/f_canvas_wall
	name = "canvas wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "f_canvas_wall-0"
	base_icon_state = "f_canvas_wall"

/turf/closed/wall/ms13/concrete/cdda/f_sandbag_wall
	name = "sandbag wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "f_sandbag_wall-0"
	base_icon_state = "f_sandbag_wall"

/turf/closed/wall/ms13/concrete/cdda/f_skin_wall
	name = "skin wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "f_skin_wall-0"
	base_icon_state = "f_skin_wall"

/turf/closed/wall/ms13/brick/cdda/t_adobe_brick_wall
	name = "adobe brick wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_adobe_brick_wall-0"
	base_icon_state = "t_adobe_brick_wall"

/turf/closed/wall/ms13/brick/cdda/t_adobe_brick_wall_halfway
	name = "adobe brick wall halfway"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_adobe_brick_wall_halfway-0"
	base_icon_state = "t_adobe_brick_wall_halfway"

/turf/closed/wall/ms13/brick/cdda/t_brick_wall
	name = "brick wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_brick_wall-0"
	base_icon_state = "t_brick_wall"

/turf/closed/wall/ms13/brick/cdda/t_brick_wall_halfway
	name = "brick wall halfway"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_brick_wall_halfway-0"
	base_icon_state = "t_brick_wall_halfway"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall
	name = "concrete wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall-0"
	base_icon_state = "t_concrete_wall"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_P
	name = "concrete wall P"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_P-0"
	base_icon_state = "t_concrete_wall_P"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_b
	name = "concrete wall b"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_b-0"
	base_icon_state = "t_concrete_wall_b"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_black
	name = "concrete wall black"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_black-0"
	base_icon_state = "t_concrete_wall_black"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_brown
	name = "concrete wall brown"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_brown-0"
	base_icon_state = "t_concrete_wall_brown"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_cyan
	name = "concrete wall cyan"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_cyan-0"
	base_icon_state = "t_concrete_wall_cyan"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_flesh
	name = "concrete wall flesh"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_flesh-0"
	base_icon_state = "t_concrete_wall_flesh"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_g
	name = "concrete wall g"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_g-0"
	base_icon_state = "t_concrete_wall_g"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_gray
	name = "concrete wall gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_gray-0"
	base_icon_state = "t_concrete_wall_gray"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_orange
	name = "concrete wall orange"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_orange-0"
	base_icon_state = "t_concrete_wall_orange"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_r
	name = "concrete wall r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_r-0"
	base_icon_state = "t_concrete_wall_r"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_w
	name = "concrete wall w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_w-0"
	base_icon_state = "t_concrete_wall_w"

/turf/closed/wall/ms13/concrete/cdda/t_concrete_wall_y
	name = "concrete wall y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_concrete_wall_y-0"
	base_icon_state = "t_concrete_wall_y"

/turf/closed/wall/ms13/concrete/cdda/t_demon_web_wall
	name = "demon web wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_demon_web_wall-0"
	base_icon_state = "t_demon_web_wall"

/turf/closed/wall/ms13/concrete/cdda/t_fungus_wall
	name = "fungus wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_fungus_wall-0"
	base_icon_state = "t_fungus_wall"

/turf/closed/wall/ms13/concrete/cdda/t_ice_wall
	name = "ice wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_ice_wall-0"
	base_icon_state = "t_ice_wall"

/turf/closed/wall/ms13/metal/cdda/t_nl_metal_wall
	name = "nl metal wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_nl_metal_wall-0"
	base_icon_state = "t_nl_metal_wall"

/turf/closed/wall/ms13/concrete/cdda/t_nm_wall_flesh
	name = "nm wall flesh"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_nm_wall_flesh-0"
	base_icon_state = "t_nm_wall_flesh"

/turf/closed/wall/ms13/concrete/cdda/t_rock_wall_half
	name = "rock wall half"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_rock_wall_half-0"
	base_icon_state = "t_rock_wall_half"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_P
	name = "sconc wall P"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_P-0"
	base_icon_state = "t_sconc_wall_P"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_b
	name = "sconc wall b"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_b-0"
	base_icon_state = "t_sconc_wall_b"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_black
	name = "sconc wall black"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_black-0"
	base_icon_state = "t_sconc_wall_black"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_brown
	name = "sconc wall brown"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_brown-0"
	base_icon_state = "t_sconc_wall_brown"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_cyan
	name = "sconc wall cyan"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_cyan-0"
	base_icon_state = "t_sconc_wall_cyan"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_g
	name = "sconc wall g"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_g-0"
	base_icon_state = "t_sconc_wall_g"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_gray
	name = "sconc wall gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_gray-0"
	base_icon_state = "t_sconc_wall_gray"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_halfway
	name = "sconc wall halfway"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_halfway-0"
	base_icon_state = "t_sconc_wall_halfway"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_orange
	name = "sconc wall orange"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_orange-0"
	base_icon_state = "t_sconc_wall_orange"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_r
	name = "sconc wall r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_r-0"
	base_icon_state = "t_sconc_wall_r"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_w
	name = "sconc wall w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_w-0"
	base_icon_state = "t_sconc_wall_w"

/turf/closed/wall/ms13/concrete/cdda/t_sconc_wall_y
	name = "sconc wall y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_sconc_wall_y-0"
	base_icon_state = "t_sconc_wall_y"

/turf/closed/wall/ms13/metal/cdda/t_scrap_wall
	name = "scrap wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_scrap_wall-0"
	base_icon_state = "t_scrap_wall"

/turf/closed/wall/ms13/metal/cdda/t_scrap_wall_halfway
	name = "scrap wall halfway"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_scrap_wall_halfway-0"
	base_icon_state = "t_scrap_wall_halfway"

/turf/closed/wall/ms13/concrete/cdda/t_screened_porch_wall
	name = "screened porch wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_screened_porch_wall-0"
	base_icon_state = "t_screened_porch_wall"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_P
	name = "strconc wall P"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_P-0"
	base_icon_state = "t_strconc_wall_P"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_b
	name = "strconc wall b"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_b-0"
	base_icon_state = "t_strconc_wall_b"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_black
	name = "strconc wall black"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_black-0"
	base_icon_state = "t_strconc_wall_black"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_brown
	name = "strconc wall brown"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_brown-0"
	base_icon_state = "t_strconc_wall_brown"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_cyan
	name = "strconc wall cyan"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_cyan-0"
	base_icon_state = "t_strconc_wall_cyan"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_g
	name = "strconc wall g"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_g-0"
	base_icon_state = "t_strconc_wall_g"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_gray
	name = "strconc wall gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_gray-0"
	base_icon_state = "t_strconc_wall_gray"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_halfway
	name = "strconc wall halfway"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_halfway-0"
	base_icon_state = "t_strconc_wall_halfway"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_orange
	name = "strconc wall orange"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_orange-0"
	base_icon_state = "t_strconc_wall_orange"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_r
	name = "strconc wall r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_r-0"
	base_icon_state = "t_strconc_wall_r"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_w
	name = "strconc wall w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_w-0"
	base_icon_state = "t_strconc_wall_w"

/turf/closed/wall/ms13/concrete/cdda/t_strconc_wall_y
	name = "strconc wall y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_strconc_wall_y-0"
	base_icon_state = "t_strconc_wall_y"

/turf/closed/wall/ms13/concrete/cdda/t_triffid_bark_wall
	name = "triffid bark wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_triffid_bark_wall-0"
	base_icon_state = "t_triffid_bark_wall"

/turf/closed/wall/ms13/wood/cdda/t_triffid_wood_wall
	name = "triffid wood wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_triffid_wood_wall-0"
	base_icon_state = "t_triffid_wood_wall"

/turf/closed/wall/ms13/concrete/cdda/t_wall
	name = "wall"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall-0"
	base_icon_state = "t_wall"

/turf/closed/wall/ms13/concrete/cdda/t_wall_P
	name = "wall P"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_P-0"
	base_icon_state = "t_wall_P"

/turf/closed/wall/ms13/concrete/cdda/t_wall_b
	name = "wall b"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_b-0"
	base_icon_state = "t_wall_b"

/turf/closed/wall/ms13/concrete/cdda/t_wall_black
	name = "wall black"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_black-0"
	base_icon_state = "t_wall_black"

/turf/closed/wall/ms13/concrete/cdda/t_wall_brown
	name = "wall brown"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_brown-0"
	base_icon_state = "t_wall_brown"

/turf/closed/wall/ms13/concrete/cdda/t_wall_cyan
	name = "wall cyan"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_cyan-0"
	base_icon_state = "t_wall_cyan"

/turf/closed/wall/ms13/concrete/cdda/t_wall_g
	name = "wall g"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_g-0"
	base_icon_state = "t_wall_g"

/turf/closed/wall/ms13/metal/cdda/t_wall_glass
	name = "wall glass"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_glass-0"
	base_icon_state = "t_wall_glass"

/turf/closed/wall/ms13/concrete/cdda/t_wall_gray
	name = "wall gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_gray-0"
	base_icon_state = "t_wall_gray"

/turf/closed/wall/ms13/metal/cdda/t_wall_metal
	name = "wall metal"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_metal-0"
	base_icon_state = "t_wall_metal"

/turf/closed/wall/ms13/concrete/cdda/t_wall_orange
	name = "wall orange"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_orange-0"
	base_icon_state = "t_wall_orange"

/turf/closed/wall/ms13/metal/cdda/t_wall_prefab_metal
	name = "wall prefab metal"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_prefab_metal-0"
	base_icon_state = "t_wall_prefab_metal"

/turf/closed/wall/ms13/concrete/cdda/t_wall_r
	name = "wall r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_r-0"
	base_icon_state = "t_wall_r"

/turf/closed/wall/ms13/concrete/cdda/t_wall_rammed_earth
	name = "wall rammed earth"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_rammed_earth-0"
	base_icon_state = "t_wall_rammed_earth"

/turf/closed/wall/ms13/concrete/cdda/t_wall_resin
	name = "wall resin"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_resin-0"
	base_icon_state = "t_wall_resin"

/turf/closed/wall/ms13/concrete/cdda/t_wall_w
	name = "wall w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_w-0"
	base_icon_state = "t_wall_w"

/turf/closed/wall/ms13/concrete/cdda/t_wall_y
	name = "wall y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wall_y-0"
	base_icon_state = "t_wall_y"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_P
	name = "wood wall P"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_P-0"
	base_icon_state = "t_wood_wall_P"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_b
	name = "wood wall b"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_b-0"
	base_icon_state = "t_wood_wall_b"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_black
	name = "wood wall black"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_black-0"
	base_icon_state = "t_wood_wall_black"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_brown
	name = "wood wall brown"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_brown-0"
	base_icon_state = "t_wood_wall_brown"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_cyan
	name = "wood wall cyan"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_cyan-0"
	base_icon_state = "t_wood_wall_cyan"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_g
	name = "wood wall g"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_g-0"
	base_icon_state = "t_wood_wall_g"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_gray
	name = "wood wall gray"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_gray-0"
	base_icon_state = "t_wood_wall_gray"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_orange
	name = "wood wall orange"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_orange-0"
	base_icon_state = "t_wood_wall_orange"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_r
	name = "wood wall r"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_r-0"
	base_icon_state = "t_wood_wall_r"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_w
	name = "wood wall w"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_w-0"
	base_icon_state = "t_wood_wall_w"

/turf/closed/wall/ms13/wood/cdda/t_wood_wall_y
	name = "wood wall y"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/walls_smooth.dmi'
	frill_icon = null
	icon_state = "t_wood_wall_y-0"
	base_icon_state = "t_wood_wall_y"
