// Ultimate Cataclysm sprites as placeable MS13 types. First generated by CDDA-Tilesets/tools/make_dm.py;
// edit freely, the script never overwrites an existing file.
// Sprites are CC BY-SA 3.0, see mojave/icons/cdda_ultimate_cataclysm/ATTRIBUTION.md

/obj/structure/window/fulltile/ms13/glass/cdda/t_curtains
	name = "curtains"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_curtains"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window
	name = "window"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_bars
	name = "window bars"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_bars"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_bars_alarm
	name = "window bars alarm"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_bars_alarm"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_boarded
	name = "window boarded"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_boarded"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_empty
	name = "window empty"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_empty"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_enhanced
	name = "window enhanced"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_enhanced"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_frame
	name = "window frame"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_frame"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_no_curtains_taped
	name = "window no curtains taped"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_no_curtains_taped"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_reinforced
	name = "window reinforced"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_reinforced"
	smoothing_flags = NONE

/obj/structure/window/fulltile/ms13/glass/cdda/t_window_taped
	name = "window taped"
	icon = 'mojave/icons/cdda_ultimate_cataclysm/windows_layered.dmi'
	icon_state = "t_window_taped"
	smoothing_flags = NONE
