#define FLOOR_PLANE -8 //MOJAVE MODULE OUTDOOR_EFFECTS
#define OVER_TILE_PLANE -7 //MOJAVE SUN EDIT - Wallening Testmerge
#define WALL_PLANE -6 //MOJAVE SUN EDIT - Wallening Testmerge
#define GAME_PLANE -5 //MOJAVE MODULE OUTDOOR_EFFECTS
#define WEATHER_EFFECT_PLANE -4 //MOJAVE MODULE OUTDOOR_EFFECTS
#define UNDER_FRILL_PLANE -3 //MOJAVE SUN EDIT - Wallening Testmerge
#define UNDER_FRILL_RENDER_TARGET "*UNDER_RENDER_TARGET" //MOJAVE SUN EDIT - Wallening Testmerge
#define FRILL_PLANE -2 //MOJAVE SUN EDIT - Wallening Testmerge
#define OVER_FRILL_PLANE -1 //MOJAVE SUN EDIT - Wallening Testmerge

//Not ever visible, place beneath everything
#define WEATHER_OVERLAY_PLANE -80 //MOJAVE MODULE OUTDOOR_EFFECTS
#define WEATHER_RENDER_TARGET "*WEATHER_OVERLAY_PLANE" //MOJAVE MODULE OUTDOOR_EFFECTS

#define GRAVITY_PULSE_PLANE -12 //MOJAVE MODULE OUTDOOR_EFFECTS

//MOJAVE SUN EDIT - Wallening Testmerge
#define FRILL_MASK_PLANE 95
#define FRILL_MASK_RENDER_TARGET "*FRILL_MASK_RENDER_TARGET"
//MOJAVE SUN EDIT - Wallening Testmerge